import {localDate,storeGet,storeSet,randomId} from './core.js?v=2.3.0';
import {cents,money,checkinStats,pocketBalance,pocketToday,wheelValues} from './daily-core.js?v=2.3.0';
import * as db from './daily-backend.js?v=2.3.0';
import {mediaBlob} from './feature-backend.js?v=2.3.0';

export function initDailySpace({$,state,node,toast,notice,ui}){
 let records=[],pockets=[],transactions=[],leaves=[],selectedPocket='',reading=null,stop=null,epoch=0,serverOffset=0;
 const urls=new Map(),uploads=new WeakMap(),panes={};
 const snap=()=>({room:state.room,userId:state.userId,epoch:state.epoch,localEpoch:epoch});
 const current=s=>s.room===state.room&&s.userId===state.userId&&s.epoch===state.epoch&&s.localEpoch===epoch;
 const name=id=>id===state.userId?'我':state.members.find(m=>m.user_id===id)?.display_name||'朋友';
 function button(text,fn,kind='text-btn'){const b=node('button',kind,text);b.type='button';b.onclick=fn;return b;}
 function label(text,input){const l=node('label','field');l.append(node('span','',text),input);return l;}
 function input(form,key,text,type='text',value='',required=false){const el=node(type==='textarea'?'textarea':'input');if(type!=='textarea')el.type=type;else el.rows=3;el.name=key;el.value=value??'';el.required=required;el.setAttribute('aria-label',text);if(type==='text')el.maxLength=120;if(type==='number'){el.min='0.01';el.step='.01';el.inputMode='decimal';}if(type==='textarea')el.maxLength=20000;form.append(label(text,el));return el;}
 function select(form,key,text,options,value){const el=node('select');el.name=key;el.setAttribute('aria-label',text);for(const [v,t] of options){const o=node('option','',t);o.value=v;el.append(o);}el.value=value??options[0][0];form.append(label(text,el));return el;}
 function check(form,key,text,value=false){const el=node('input');el.type='checkbox';el.name=key;el.checked=value;const l=node('label','check-field');l.append(el,document.createTextNode(text));form.append(l);return el;}
 function toolbar(title,add){const bar=node('div','daily-toolbar');bar.append(node('h3','',title),button('＋',add,'round-btn'));return bar;}
 // Query selector is kept separate from the app's getElementById helper.
 const grid=document.querySelector('.relation-grid');
 function panel(id,title,symbol,caption){const section=node('section','space-page');section.id=id;section.dataset.spacePanel=title;section.hidden=true;const content=node('div','sheet daily-content');section.append(content);$('spacePages').append(section);ui.registerPanel(id,title);const b=button('',()=>{ui.openFeature(id);void refresh();},'relation-card');b.id=id+'Btn';const text=node('span');text.append(node('b','',title),node('small','',caption));b.append(node('span','feature-symbol',symbol),text,node('i','','›'));grid.append(b);return content;}
 for(const [id,title,symbol,caption,kind] of [['checkinSpace','一起打卡','✓','一人一步，一起坚持','goal'],['ledgerSpace','日常记账','¥','记下日常的花费','ledger'],['pocketSpace','荷包','♡','一点点靠近共同目标','pocket'],['todoSpace','待办','☑','把惦记的事情做完','todo'],['activitySpace','共同活动','◷','书、课程与追剧记录','activity']]){
  const content=panel(id,title,symbol,caption),status=node('p','sheet-note'),editor=node('div','daily-editor'),list=node('div','daily-list');editor.hidden=true;content.append(toolbar(kind==='pocket'?'我们的目标':title,()=>kind==='pocket'?pocketCreate():edit(kind)),status,editor,list);panes[kind]={id,content,status,editor,list};
 }
 const diaryList=node('div','daily-list diary-journal'),diaryEditor=node('div','daily-editor'),diaryStatus=node('p','sheet-note');diaryEditor.hidden=true;diaryList.id='diaryJournal';$('diaryTools').after(diaryStatus,diaryEditor,diaryList);panes.diary={id:'diarySpace',content:$('diarySpace'),status:diaryStatus,editor:diaryEditor,list:diaryList};
 $('writeFromView').onclick=()=>edit('diary');
 for(const b of document.querySelectorAll('[data-diary-filter]'))b.addEventListener('click',()=>renderDiary());$('diaryDate').addEventListener('change',renderDiary);
 const ledgerMonth=input(panes.ledger.content,'month','月份','month',localDate().slice(0,7));panes.ledger.list.before(ledgerMonth.parentElement);ledgerMonth.onchange=renderLedger;
 const statusMessage=e=>e.message?.includes('Insufficient balance')?'金额超过当前荷包余额。':e.code==='42501'?'当前账号无法修改这条记录，请核对登录账号。':['42P01','42703','PGRST202','PGRST205'].includes(e.code)?'暂时无法读取，请联系房间创建者完成数据更新。':e.message||'没有保存成功，请检查网络后重试。';
 function requireAccount(){if(!state.ready||!state.secure){toast('这些共同记录需要在邀请房间里使用。');return false;}return true;}
 async function refresh(){
  if(!state.ready||!state.secure)return;if(reading)return reading;const s=snap();
  const work=(async()=>{try{const started=Date.now();const [a,b,c,d,clock]=await Promise.all([...['space_entries','pockets','pocket_entries','pocket_leaves'].map(t=>db.listRows(t,s.room)),db.rpc('mailbox_space_clock',{p_room:s.room})]);if(!current(s))return;serverOffset=Date.parse(clock.server_now)-(started+Date.now())/2;records=a;pockets=b;transactions=c;leaves=d;for(const p of Object.values(panes))p.status.textContent='';renderAll();}catch(e){if(current(s))for(const p of Object.values(panes))p.status.textContent=statusMessage(e);}finally{if(current(s))reading=null;}})();reading=work;return work;
 }
 const entries=kind=>records.filter(r=>r.kind===kind).sort((a,b)=>b.event_date.localeCompare(a.event_date)||b.created_at.localeCompare(a.created_at));
 function empty(box,text){if(!box.children.length)box.append(node('p','daily-empty',text));}
 function viewMedia(container,media,s=snap()){
  for(const m of media||[]){const open=button(m.type==='image'?'查看图片':m.type==='video'?'播放视频':m.name,async()=>{open.disabled=true;try{let url=urls.get(m.path);if(!url){url=URL.createObjectURL(await mediaBlob(s.room,m.path));if(!current(s)){URL.revokeObjectURL(url);return;}urls.set(m.path,url);}const tag=m.type==='image'?'img':m.type==='video'?'video':m.type==='audio'?'audio':'a',el=node(tag,'daily-media');if(tag==='a'){el.href=url;el.download=m.name;el.textContent='下载 '+m.name;}else{el.src=url;if(tag==='img')el.alt=m.name;else el.controls=true;}open.replaceWith(el);}catch(e){if(current(s)){open.disabled=false;toast(statusMessage(e));}}});container.append(open);}
 }
 function rowCard(row){const card=node('article','daily-row');card.dataset.entryId=row.id;const meta=node('small','daily-meta',`${row.event_date} · ${name(row.owner_user_id)}${row.visibility==='private'?' · 仅自己':''}`);card.append(meta);if(row.title)card.append(node('h4','',row.title));if(row.body)card.append(node('p','daily-body',row.body));if(row.kind==='diary')card.append(node('small','', [row.data.mood,...(row.data.tags||[])].filter(Boolean).join(' · ')));viewMedia(card,row.data.media);if(row.owner_user_id===state.userId){const actions=node('div','daily-actions');actions.append(button('编辑',()=>edit(row.kind,row)),button('删除',async()=>{const s=snap();if(!await notice('删除这条记录？','聊天留言不会受影响。','删除',true)||!current(s))return;try{await db.deleteEntry(row);if(current(s))await refresh();}catch(e){if(current(s))toast(statusMessage(e));}}));card.append(actions);}return card;}
 function renderDiary(){const p=panes.diary;p.list.replaceChildren();const category=state.diaryFilter||'all',date=$('diaryDate').value;$('diaryEntries').hidden=category!=='all';for(const r of entries('diary'))if((!date||r.event_date===date)&&(category==='all'||r.data.category===category))p.list.append(rowCard(r));if(category!=='all')empty(p.list,'这一类还没有日记。');}
 function renderGoals(){const box=panes.goal.list;box.replaceChildren();for(const goal of entries('goal')){const card=node('article','daily-row');card.append(node('h4','',goal.title),node('p','daily-body',goal.body));const members=goal.visibility==='private'?[{user_id:state.userId}]:state.members;
  for(const m of members){const stats=checkinStats(records,goal,m.user_id),line=node('p','goal-progress',`${name(m.user_id)} · ${stats.today?'今日已完成':'今日待打卡'} · 连续 ${stats.streak} 天 · ${stats.rate}%`);card.append(line);}
  card.append(button('记录今天',()=>edit('checkin',null,goal),'btn primary'));if(goal.owner_user_id===state.userId)card.append(button('修改目标',()=>edit('goal',goal)));
  const history=node('details'),summary=node('summary','','打卡历史');history.append(summary);for(const r of entries('checkin').filter(r=>r.data.goal===goal.id))history.append(rowCard(r));card.append(history);box.append(card);
 }empty(box,'先定一个想一起坚持的小目标。');}
 function renderLedger(){const box=panes.ledger.list,month=ledgerMonth.value;box.replaceChildren();const rows=entries('ledger').filter(r=>r.event_date.startsWith(month));const total=rows.reduce((n,r)=>n+Number(r.data.cents),0);box.append(node('div','ledger-total',`本月 ¥ ${money(total)}`));const summary=new Map();for(const r of rows)summary.set(r.data.category,(summary.get(r.data.category)||0)+r.data.cents);for(const [k,v] of summary)box.append(node('small','ledger-category',`${k}  ¥ ${money(v)}`));for(const r of rows){const c=rowCard(r);c.prepend(node('strong','ledger-amount',`¥ ${money(r.data.cents)}`));c.append(node('small','',`${r.data.category} · ${name(r.data.paid_by)}支付`));box.append(c);}if(!rows.length)box.append(node('p','daily-empty','这一月还没有记录。'));}
 function renderTodos(){const box=panes.todo.list;box.replaceChildren();for(const r of entries('todo').sort((a,b)=>Number(a.data.done)-Number(b.data.done)||a.event_date.localeCompare(b.event_date))){const card=rowCard(r),toggle=node('input');toggle.type='checkbox';toggle.checked=!!r.data.done;toggle.disabled=r.owner_user_id!==state.userId;toggle.setAttribute('aria-label','完成 '+r.title);toggle.onchange=async()=>{const s=snap();toggle.disabled=true;try{await db.saveEntry({...r,data:{...r.data,done:toggle.checked}});if(current(s))await refresh();}catch(e){if(current(s)){toggle.checked=!toggle.checked;toast(statusMessage(e));}}finally{if(current(s))toggle.disabled=false;}};card.classList.toggle('is-done',!!r.data.done);card.prepend(toggle);box.append(card);}empty(box,'今天，有什么想慢慢完成的？');}
 function renderActivities(){const box=panes.activity.list;box.replaceChildren();for(const r of entries('activity')){const c=rowCard(r);c.append(node('small','',`${({book:'一起看书',course:'一起上课',drama:'一起追剧'})[r.data.category]} · ${r.data.progress||'刚刚开始'}`));box.append(c);}empty(box,'留下一本书、一堂课，或一起看过的一集。');}
 function edit(kind,row=null,goal=null){if(!requireAccount())return;const target=kind==='checkin'?panes.goal:panes[kind];ui.openFeature(target.id);const form=node('form','daily-form');target.editor.replaceChildren(form);target.editor.hidden=false;const s=snap(),id=row?.id||randomId();const currentEdit=()=>current(s)&&form.isConnected;const data={...(row?.data||{})};const controls={};form.append(node('h4','',row?'编辑记录':({diary:'写日记',goal:'新的共同目标',checkin:'今天的一步',ledger:'记一笔',todo:'写下待办',activity:'记录共同活动'})[kind]));
  if(kind!=='checkin')controls.title=input(form,'title',kind==='ledger'?'这笔花费':kind==='diary'?'标题（可留空）':'名称','text',row?.title||'',!['diary','ledger'].includes(kind));
  controls.date=input(form,'date',kind==='todo'?'计划日期':'日期','date',row?.event_date||localDate(),true);
  if(kind==='diary'){controls.category=select(form,'category','分类',[['daily','日常'],['mood','心情'],['essay','随笔']],data.category);controls.mood=input(form,'mood','心情','text',data.mood||'');controls.tags=input(form,'tags','标签（用逗号分开）','text',(data.tags||[]).join('，'));}
  if(kind==='ledger'){controls.amount=input(form,'amount','金额','number',data.cents?money(data.cents).replaceAll(',',''):'',true);controls.category=input(form,'category','分类','text',data.category||'日常',true);controls.paid=select(form,'paid','谁支付',state.members.map(m=>[m.user_id,name(m.user_id)]),data.paid_by||state.userId);}
  if(kind==='activity'){controls.category=select(form,'category','一起做什么',[['book','一起看书'],['course','一起上课'],['drama','一起追剧']],data.category);controls.progress=input(form,'progress','看到 / 学到哪里','text',data.progress||'');}
  controls.body=input(form,'body','记录 / 备注','textarea',row?.body||'');
  if(kind!=='checkin')controls.visibility=select(form,'visibility','可见范围',[['shared','我们都能看见'],['private','仅自己可见']],row?.visibility||'shared');
  if(['goal','todo'].includes(kind))controls.remind=check(form,'remind','到日子提醒我',data.remind!==false);
  if(['diary','checkin','activity'].includes(kind)){controls.media=input(form,'media','添加图片 / 视频','file');controls.media.multiple=true;controls.media.accept='image/*,video/*';if(data.media?.length){viewMedia(form,data.media);controls.removeMedia=check(form,'removeMedia','移除原有附件');}}
  const status=node('p','sheet-note'),save=node('button','btn primary','保存');save.type='submit';form.append(status,save,button('取消',()=>target.editor.hidden=true));
  form.onsubmit=async event=>{event.preventDefault();if(save.disabled||!currentEdit())return;save.disabled=true;status.textContent='正在保存…';try{const media=controls.removeMedia?.checked?[]:[...(data.media||[])];for(const file of controls.media?.files||[]){if(media.length>=8)throw new Error('一条记录最多 8 个附件。');media.push(await db.upload(file,s,uploads));if(!currentEdit())return;}const values={...data,media};if(kind==='diary')Object.assign(values,{category:controls.category.value,mood:controls.mood.value,tags:controls.tags.value.split(/[,，]/).map(x=>x.trim()).filter(Boolean).slice(0,20)});if(kind==='ledger')Object.assign(values,{cents:cents(controls.amount.value),category:controls.category.value,paid_by:controls.paid.value});if(kind==='activity')Object.assign(values,{category:controls.category.value,progress:controls.progress.value});if(controls.remind)values.remind=controls.remind.checked;if(kind==='checkin')values.goal=goal?.id||data.goal;
   const saved={id,revision:row?.revision||0,room_id:s.room,owner_user_id:s.userId,kind,title:controls.title?.value.trim()||row?.title||goal?.title||'',body:controls.body.value,event_date:controls.date.value,visibility:controls.visibility?.value||row?.visibility||goal?.visibility||'shared',data:values};await db.saveEntry(saved);if(!currentEdit())return;target.editor.hidden=true;toast('已经记下了。');await refresh();
  }catch(e){if(currentEdit())status.textContent=statusMessage(e);}finally{if(currentEdit())save.disabled=false;}};form.querySelector('input,textarea')?.focus();
 }
 function pocketRequestKey(s){return `pocket-request.${s.room}.${s.userId}`;}
 async function pocketRequest(method,params,s=snap()){
  const key=pocketRequestKey(s),pending=storeGet(key,null);
  if(pending&&(pending.method!==method||JSON.stringify(pending.params)!==JSON.stringify(params)))throw new Error('上一笔记录还未确认，请先返回荷包核对或继续提交。');
  if(!storeSet(key,{method,params}))throw new Error('无法保留提交编号，请允许本机存储后再记录。');
  const clear=()=>{const latest=storeGet(key,null);if(latest?.method===method&&JSON.stringify(latest.params)===JSON.stringify(params))storeSet(key,null);};try{const result=await db.rpc(method,params);clear();return result;}catch(e){if(['22023','42501','23502','23514'].includes(e.code))clear();throw e;}
 }
 function pendingPocket(box){const s=snap(),pending=storeGet(pocketRequestKey(s),null);if(!pending)return;const id=pending.params.p_id,known=[...pockets,...transactions,...leaves].find(r=>r.id===id);if(known&&['deposit','withdraw',undefined].includes(pending.params.p_action)){storeSet(pocketRequestKey(s),null);return;}
  const card=node('aside','pocket-pending');card.append(node('strong','','上一笔记录还未确认'),node('p','',pending.params.p_cents?`¥ ${money(pending.params.p_cents)} · ${pending.params.p_reason||''}`:'有一条尚未确认的荷包记录。'));
  const retry=button('继续提交同一笔',async()=>{retry.disabled=true;try{await pocketRequest(pending.method,pending.params,s);if(current(s)){panes.pocket.editor.hidden=true;await refresh();}}catch(e){if(current(s))toast(statusMessage(e));}finally{retry.disabled=false;}});card.append(retry);box.append(card);
 }
 function selected(){return pockets.find(p=>p.id===selectedPocket)||pockets[0];}
 function renderPockets(){const box=panes.pocket.list;box.replaceChildren();pendingPocket(box);if(!pockets.length){box.append(node('p','daily-empty','和你一起，存下想要的生活。'),button('创建第一个荷包',pocketCreate,'btn primary'));return;}const p=selected();selectedPocket=p.id;
  if(pockets.length>1){const picker=select(box,'pocket','我们的目标',pockets.map(p=>[p.id,p.title]),p.id);picker.onchange=()=>{selectedPocket=picker.value;renderPockets();};}
  const rows=transactions.filter(r=>r.pocket_id===p.id),balance=pocketBalance(rows),hero=node('div','pocket-hero');hero.append(node('span','pocket-kicker','FOR OUR FUTURE'),node('h3','',p.title));if(p.cover_path)viewMedia(hero,[{path:p.cover_path,type:'image',name:'荷包封面'}]);hero.append(node('p','',p.note||'一点一滴，走向共同的期待。'));box.append(hero);
  const amount=node('div','pocket-amount');amount.append(node('strong','',`¥ ${money(balance)}`),node('small','',` / ${money(p.target_cents)}`));const progress=node('progress');progress.max=p.target_cents;progress.value=Math.min(balance,p.target_cents);box.append(amount,progress,node('p','sheet-note',`${p.mode==='daily'?`每人每日 ¥ ${money(p.daily_cents)}`:'随心存'}${p.due_date?' · 目标日 '+p.due_date:''}`));
  if(balance>=p.target_cents){const complete=node('div','pocket-complete');complete.append(node('span','','✦'),node('h3','','我们做到了！'),node('p','',`“${p.title}”已达成 · ${rows.filter(r=>r.kind==='deposit').length} 次存入`),button('再定一个目标',pocketCreate,'btn primary'));box.append(complete);}
  const controls=node('div','daily-actions');controls.append(button('＋ 存一笔',()=>pocketForm('deposit',p),'btn primary'),button('取出',()=>pocketForm('withdraw',p),'btn ghost'),button('写假条',()=>pocketForm('leave',p)),button('转盘存钱',()=>wheel(p)));box.append(controls);
  const qr=node('details');qr.append(node('summary','','查看收款码'));viewMedia(qr,[{path:p.qr_path,type:'image',name:'荷包收款码'}]);box.append(qr,node('p','sheet-note','使用收款码在支付软件完成转账，再回来记录。这里显示双方填写的存取记录。'));
  const today=node('section','pocket-today');today.append(node('h4','','今日存钱'));for(const m of pocketToday(p,rows,leaves.filter(l=>l.pocket_id===p.id),state.members)){const line=node('p','',`${name(m.user)} · ${m.leave?'假期中：'+m.leave.reason:m.done?'已完成':'待存入'} · ¥ ${money(m.amount)}`);line.classList.toggle('needs-attention',!m.done);today.append(line);}box.append(today);
  for(const r of rows.filter(r=>r.status==='pending')){const c=node('article','pocket-pending');c.append(node('strong','',`${name(r.owner_user_id)} · 申请取出 ¥ ${money(r.cents)}`),node('p','',r.reason),node('small','',`冷静期至 ${new Date(r.available_at).toLocaleString('zh-CN')}`));const countdown=node('p','pocket-countdown');countdown.dataset.until=r.available_at;c.append(countdown);if(r.owner_user_id===state.userId){const confirm=button('到期再次确认',async()=>{const s=snap();if(!await notice('仍然需要取出吗？',`记录取出 ¥ ${money(r.cents)}；还想留着，可以取消申请。`,'确认取出',true)||!current(s))return;await pocketAction(p,r,'confirm');});confirm.dataset.until=r.available_at;c.append(confirm,button('取消，继续存着',()=>pocketAction(p,r,'cancel')));}box.append(c);}
  const history=node('details');history.open=true;history.append(node('summary','','一起存下的日子'));for(const r of [...rows].sort((a,b)=>b.created_at.localeCompare(a.created_at))){const line=node('article','daily-row');line.append(node('small','daily-meta',`${new Date(r.created_at).toLocaleString('zh-CN')} · ${name(r.owner_user_id)}`),node('strong','',`${r.kind==='deposit'?'+':'−'} ¥ ${money(r.cents)} · ${({settled:'已记录',pending:'冷静期',cancelled:'已取消'})[r.status]}`),node('p','daily-body',r.reason));history.append(line);}for(const l of leaves.filter(l=>l.pocket_id===p.id))history.append(node('p','sheet-note',`${name(l.owner_user_id)}的假条 · ${l.date_start}～${l.date_end} · ${l.reason}`));box.append(history);updateCountdowns();
 }
 function updateCountdowns(){for(const el of panes.pocket.list.querySelectorAll('[data-until]')){const seconds=Math.max(0,Math.ceil((Date.parse(el.dataset.until)-Date.now()-serverOffset)/1000));if(el.tagName==='BUTTON'){el.disabled=seconds>0;continue;}el.textContent=seconds?`还需 ${String(Math.floor(seconds/3600)).padStart(2,'0')}:${String(Math.floor(seconds/60)%60).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`:'冷静期结束，还需要这笔钱吗？';}}
 setInterval(()=>{if(!document.hidden&&state.spacePanel==='pocketSpace')updateCountdowns();},1000);
 async function pocketAction(p,r,action){const s=snap();try{await pocketRequest('mailbox_pocket_action',{p_pocket:p.id,p_id:r.id,p_action:action},s);if(current(s)){toast(action==='confirm'?'取出已记录。':'已经取消申请，继续存着。');await refresh();}}catch(e){if(current(s))toast(e.message?.includes('Cooling')?'冷静期还未结束，或余额已变化，请稍后刷新再确认。':statusMessage(e));}}
 function pocketCreate(){if(!requireAccount())return;ui.openFeature('pocketSpace');const pane=panes.pocket,form=node('form','daily-form');pane.editor.hidden=false;pane.editor.replaceChildren(form);const s=snap(),id=randomId();const currentEdit=()=>current(s)&&form.isConnected;form.append(node('h4','','一起定一个目标'));const title=input(form,'title','荷包名称','text','',true),target=input(form,'target','目标金额','number','',true),due=input(form,'due','目标日期','date'),note=input(form,'note','关于这个目标','textarea');note.maxLength=1000;const mode=select(form,'mode','存钱方式',[['daily','每日定额'],['free','随心存']]),daily=input(form,'daily','每人每日金额','number','10');mode.onchange=()=>daily.parentElement.hidden=mode.value!=='daily';const qr=input(form,'qr','收款码（必选）','file','',true);qr.accept='image/*';const cover=input(form,'cover','封面图片（可选）','file');cover.accept='image/*';const status=node('p','sheet-note'),save=node('button','btn primary','创建荷包');save.type='submit';form.append(status,save,button('取消',()=>pane.editor.hidden=true));form.onsubmit=async e=>{e.preventDefault();if(save.disabled||!currentEdit())return;save.disabled=true;status.textContent='正在保存…';try{const total=cents(target.value),perDay=mode.value==='daily'?cents(daily.value):0;const qrMedia=await db.upload(qr.files[0],s,uploads);if(!currentEdit())return;const coverMedia=cover.files[0]?await db.upload(cover.files[0],s,uploads):null;if(!currentEdit())return;await pocketRequest('mailbox_create_pocket',{p_id:id,p_room:s.room,p_title:title.value.trim(),p_target:total,p_daily:perDay,p_mode:mode.value,p_due:due.value||null,p_note:note.value,p_qr:qrMedia.path,p_cover:coverMedia?.path||null},s);if(currentEdit()){selectedPocket=id;pane.editor.hidden=true;await refresh();toast('新的目标，已经放进荷包了。');}}catch(e){if(currentEdit())status.textContent=statusMessage(e);}finally{if(currentEdit())save.disabled=false;}};
 }
 function pocketForm(action,p,initial=''){const pane=panes.pocket,form=node('form','daily-form');pane.editor.hidden=false;pane.editor.replaceChildren(form);const s=snap(),id=randomId();const currentEdit=()=>current(s)&&form.isConnected;form.append(node('h4','',action==='leave'?'给自己放个假':action==='deposit'?'存入一份期待':'申请取出'));let amount,start,end,hours,emergency,confirmed;
  if(action==='leave'){start=input(form,'start','开始日期','date',localDate(),true);end=input(form,'end','结束日期','date',localDate(),true);}else amount=input(form,'amount','金额','number',initial,true);
  const reason=input(form,'reason',action==='deposit'?'留一句话（可选）':'简单说明原因','textarea','',action!=='deposit');reason.maxLength=1000;
  if(action==='withdraw'){hours=select(form,'hours','冷静期',[['24','24 小时'],['48','48 小时']]);emergency=check(form,'emergency','紧急需求，填写原因后直接记录取出');emergency.onchange=()=>hours.parentElement.hidden=emergency.checked;}
  if(action==='deposit'){viewMedia(form,[{path:p.qr_path,type:'image',name:'荷包收款码'}]);confirmed=check(form,'confirmed','我已在支付软件完成这笔转账');confirmed.required=true;}
  const status=node('p','sheet-note'),save=node('button','btn primary',action==='leave'?'留下假条':action==='deposit'?'确认记录存入':'提交取出申请');save.type='submit';form.append(status,save,button('取消',()=>pane.editor.hidden=true));form.onsubmit=async e=>{e.preventDefault();if(save.disabled||!currentEdit())return;save.disabled=true;try{if(action==='leave')await pocketRequest('mailbox_pocket_leave',{p_pocket:p.id,p_id:id,p_start:start.value,p_end:end.value,p_reason:reason.value},s);else await pocketRequest('mailbox_pocket_action',{p_pocket:p.id,p_id:id,p_action:action,p_cents:cents(amount.value),p_reason:reason.value,p_hours:Number(hours?.value||24),p_emergency:emergency?.checked||false},s);if(!currentEdit())return;pane.editor.hidden=true;await refresh();toast(action==='withdraw'&&!emergency.checked?'申请已记录，冷静期结束后再确认。':'已经记下了。');}catch(e){if(currentEdit())status.textContent=statusMessage(e);}finally{if(currentEdit())save.disabled=false;}};form.scrollIntoView({block:'start',behavior:'smooth'});
 }
 function wheel(p){const pane=panes.pocket,form=node('form','daily-form');pane.editor.hidden=false;pane.editor.replaceChildren(form);form.append(node('h4','','今天存多少？'));const min=input(form,'min','最小金额','number','1',true),max=input(form,'max','最大金额','number','50',true),count=input(form,'count','生成数量','number','8',true);count.step='1';count.min='2';count.max='24';const disk=node('div','savings-wheel'),result=node('p','wheel-result'),spin=node('button','btn primary','生成并转动');spin.type='submit';const wheelWrap=node('div','wheel-wrap');wheelWrap.append(disk);form.append(wheelWrap,result,spin,button('收起',()=>pane.editor.hidden=true));let values=[],chosen=0,rotation=0;const s=snap();form.onsubmit=async e=>{e.preventDefault();if(spin.disabled)return;try{values=wheelValues(min.value,max.value,count.value);}catch(e){toast(e.message);return;}disk.replaceChildren();values.forEach((v,i)=>{const label=node('span','',money(v));label.style.setProperty('--turn',`${i*360/values.length}deg`);disk.append(label);});chosen=Math.floor(crypto.getRandomValues(new Uint32Array(1))[0]/4294967296*values.length);rotation+=1440+(360-rotation%360)+(360-chosen*360/values.length);disk.style.transform=`rotate(${rotation}deg)`;spin.disabled=true;result.textContent='';await new Promise(r=>setTimeout(r,1600));if(!current(s))return;result.textContent=`今天存 ¥ ${money(values[chosen])}`;result.append(button('用这个金额存入',()=>pocketForm('deposit',p,(values[chosen]/100).toFixed(2)),'btn primary'));spin.disabled=false;};}
 const reminderBox=node('div','daily-reminders');reminderBox.hidden=true;document.querySelector('.relation-days').after(reminderBox);
 function renderAll(){renderDiary();renderGoals();renderLedger();renderTodos();renderActivities();renderPockets();reminders();}
 function reminders(){const due=entries('todo').filter(r=>r.owner_user_id===state.userId&&!r.data.done&&r.data.remind&&r.event_date<=localDate());const savings=pockets.flatMap(p=>pocketToday(p,transactions.filter(r=>r.pocket_id===p.id),leaves.filter(l=>l.pocket_id===p.id),state.members).filter(m=>!m.done).map(m=>({p,m})));const goals=entries('goal').filter(g=>g.data.remind!==false&&g.event_date<=localDate()&&!checkinStats(records,g,state.userId).today);const items=[...goals.map(g=>({id:'goal-'+g.id,text:'今日打卡：'+g.title,kind:'goal'})),...due.map(r=>({id:'todo-'+r.id,text:r.title,kind:'todo'})),...savings.map(({p,m})=>({id:`pocket-${p.id}-${m.user}`,text:`${name(m.user)}今天还没完成「${p.title}」`,kind:'pocket'}))];reminderBox.replaceChildren();reminderBox.hidden=!items.length;for(const item of items)reminderBox.append(button('○ '+item.text,()=>ui.openFeature(panes[item.kind].id)));const key=`daily-seen.${state.room}.${state.userId}.${localDate()}`,seen=new Set(storeGet(key,[])),fresh=items.filter(r=>!seen.has(r.id));if(fresh.length){toast(fresh[0].text+(fresh.length>1?` · 还有 ${fresh.length-1} 项提醒`:''));storeSet(key,[...seen,...fresh.map(r=>r.id)]);}document.dispatchEvent(new CustomEvent('mailbox:daily-reminders',{detail:items}));}
 function reset(){epoch++;reading=null;stop?.();stop=null;records=[];pockets=[];transactions=[];leaves=[];selectedPocket='';for(const url of urls.values())URL.revokeObjectURL(url);urls.clear();reminderBox.hidden=true;reminderBox.replaceChildren();for(const p of Object.values(panes)){p.editor.replaceChildren();p.editor.hidden=true;p.list.replaceChildren();p.status.textContent='';}}
 function ready(){if(state.secure){const s=snap();stop=db.watch(s.room,()=>{if(current(s))void refresh();});void refresh();}}
 document.addEventListener('mailbox:space-open',()=>{if(state.ready)void refresh();});document.addEventListener('visibilitychange',()=>{if(!document.hidden)void refresh();});setInterval(()=>{if(!document.hidden&&!$('relationSpace').inert)void refresh();},20000);
 return {reset,ready,refresh,entries:()=>records};
}
