import {poetryMarkup,applyPoetry} from './poetry.js?v=2.6.1';
import {randomId,storeGet,storeSet} from './core.js?v=2.6.1';
import {normalizeFrames} from './memory-core.js?v=2.6.1';
import {createFilmAudio} from './film-audio.js?v=2.6.1';
import * as db from './memory-backend.js?v=2.6.1';
import {upload} from './daily-backend.js?v=2.6.1';
import {mediaBlob} from './feature-backend.js?v=2.6.1';

export function initFilmSpace({$,state,node,toast,notice,ui,memories}){
 const pane=node('section','space-page');pane.id='filmSpace';pane.hidden=true;pane.innerHTML='<div class="sheet film-space"><div class="daily-toolbar"><h3>我的回忆胶片</h3><button id="filmNew" class="text-btn">＋ 新的一卷</button></div><div id="filmList"></div><div id="filmEditor" hidden><label class="field">这卷胶片的名字<input id="filmTitle" maxlength="120" value="我们的片段"/></label><div class="film-editor-actions"><button id="filmAdd">＋ 选择回忆</button><button id="filmSave">保存胶片</button><button id="filmPreview">▷ 预览放映</button></div><div id="filmFrames"></div><label class="file-picker">选择背景音乐（20 MB 以内）<input id="filmBgm" type="file" accept="audio/*"/></label><p id="filmBgmName"></p><button id="filmRemoveBgm" class="text-btn">移除配乐</button><p id="filmSaveStatus" role="status"></p></div><p id="filmStatus" class="sheet-note" role="status"></p><div id="filmProjector" hidden><header class="film-projector-title"><h3>胶片放映</h3><span>MEMORY FILM</span></header><div class="film-projection-stage"><div class="film-machine" aria-hidden="true"><i class="film-beam"></i></div><div id="filmGate"><div id="filmScene"></div><canvas id="filmGrain" width="180" height="120"></canvas><div class="film-vignette"></div><div class="film-leak"></div><div class="film-scratch"></div><div class="film-flash"></div></div><button id="filmDetailOpen" class="text-btn">查看这一幕 ↗</button></div><div class="film-times"><span id="filmElapsed">0:00</span><span id="filmTotal">0:00</span></div><input id="filmProgress" class="film-progress" aria-label="胶片播放位置" type="range" min="0" max="1" step="1" value="0"/><div id="filmControls"><button id="filmExit" aria-label="返回胶片编辑">‹</button><button id="filmRewind" aria-label="倒带">↶</button><button id="filmPrev" aria-label="上一幕">│◀</button><button id="filmPlay">暂停</button><button id="filmNext" aria-label="下一幕">▶│</button><select id="filmSpeed" aria-label="放映速度"><option value="0.5">0.5×</option><option value="1" selected>1×</option><option value="1.5">1.5×</option><option value="2">2×</option></select></div><div class="film-options"><span id="filmPosition"></span><label>音效<select id="filmSound"><option value="off">关闭</option><option value="light" selected>轻微</option><option value="immersive">沉浸</option></select></label><button id="filmFullscreen">全屏</button></div><div id="filmTimeline" class="film-timeline" aria-label="胶片场景"></div></div><section id="filmDetail" class="film-detail" hidden></section><audio id="filmBgmAudio" loop></audio></div>';
 const editorial=node('div','film-poem');editorial.innerHTML=poetryMarkup(24,true);pane.querySelector('.daily-toolbar').after(editorial);applyPoetry(editorial);pane.querySelector('#filmFrames').after(pane.querySelector('.film-editor-actions'));
 $('spacePages').append(pane);ui.registerPanel('filmSpace','回忆胶片');const entry=node('button','relation-card');entry.innerHTML='<span class="feature-symbol">▥</span><span><b>回忆胶片</b><small>挑选、编排，重看那一天</small></span><i>›</i>';entry.id='filmSpaceBtn';document.querySelector('.relation-grid').append(entry);
 const sound=createFilmAudio(),bgm=$('filmBgmAudio'),uploads=new WeakMap();bgm.onplay=()=>sound.duck(true);bgm.onpause=()=>sound.duck(hasOriginalSound());let editing=0,film=null,films=[],epoch=0,preview=[],index=0,playing=false,rewinding=false,frameElapsed=0,lastTime=0,raf=0,rewindTimer=0,grainTime=0,controlTimer=0,holdTimer=0,longHold=false,bgmUrl='',generation=0,sceneId=0;
 const snap=()=>({room:state.room,userId:state.userId,epoch:state.epoch,localEpoch:epoch}),current=s=>s.room===state.room&&s.userId===state.userId&&s.epoch===state.epoch&&s.localEpoch===epoch;
 const draftKey=()=>`film-draft.${state.room}.${state.userId}`;
 function button(text,fn){const b=node('button','text-btn',text);b.type='button';b.onclick=fn;return b;}
 function keep(){editing++;if(film){film.title=$('filmTitle').value;storeSet(draftKey(),film);}}
 async function open(ids=[]){if(!state.secure){toast('回忆胶片保存在邀请房间里。');return;}ui.openFeature('filmSpace');const s=snap();try{await memories.refresh();if(!current(s))return;films=await db.films(s.room);if(!current(s))return;list();if(ids.length){film ||= {id:randomId(),room_id:s.room,owner_user_id:s.userId,title:'我们的片段',frames:[],bgm:null};const included=new Set(film.frames.map(f=>f.source));film.frames.push(...ids.filter(id=>!included.has(id)).map(source=>({source,seconds:4})));edit();keep();}else if(!film){const saved=storeGet(draftKey(),null);if(saved?.room_id===s.room&&saved.owner_user_id===s.userId){film=saved;edit();}}$('filmStatus').textContent='';}catch(e){if(current(s))$('filmStatus').textContent=e.message||'暂时无法读取胶片。';}}
 entry.onclick=()=>void open();memories.onFilm(ids=>void open(ids));
 function list(){$('filmList').replaceChildren(...films.map(row=>{const el=node('div','film-saved');el.append(button(row.title,()=>{stopPreview();film=structuredClone(row);edit();keep();}),node('small','',`${row.frames.length} 幕`),button('删除',async()=>{const s=snap();if(!await notice('删除这一卷胶片？','原始回忆仍然保留。','删除胶片',true)||!current(s))return;try{await db.deleteFilm(row);if(current(s)){films=films.filter(f=>f.id!==row.id);if(film?.id===row.id){film=null;$('filmEditor').hidden=true;storeSet(draftKey(),null);}list();}}catch(e){toast(e.message);}}));return el;}));}
 function edit(){if(!film)return;film.frames=normalizeFrames(film.frames);$('filmEditor').hidden=false;$('filmTitle').value=film.title;$('filmBgmName').textContent=film.bgm?.name||'未选择背景音乐';$('filmRemoveBgm').hidden=!film.bgm;$('filmFrames').replaceChildren();for(const [i,f] of film.frames.entries()){const memory=memories.rows.find(r=>r.id===f.source),row=node('article','film-edit-frame');row.dataset.frame=String(i);row.draggable=true;const label=node('div');label.append(node('small','',String(i+1).padStart(2,'0')+' / '+(memory?.date||'')),node('p','',(memory?.title||memory?.body||'回忆来源 '+f.source).slice(0,100)));const grip=button('⠿',()=>{});grip.className='film-drag-handle';grip.setAttribute('aria-label','拖动第 '+(i+1)+' 幕排序');const thumb=node('div','film-frame-thumb');if(memory?.media?.length)void memories.getMedia(memory,thumb);else thumb.append(node('span','',(memory?.body||memory?.title||'这一刻').slice(0,50)));row.append(node('span','film-frame-number',String(i+1).padStart(2,'0')),grip,thumb,label);let dragging=false;grip.onpointerdown=e=>{grip.setPointerCapture(e.pointerId);dragging=true;row.classList.add('dragging');};grip.onpointermove=e=>{if(!dragging)return;e.preventDefault();const under=document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-frame]');$('filmFrames').querySelectorAll('.drop-target').forEach(el=>el.classList.remove('drop-target'));if(under&&under!==row)under.classList.add('drop-target');};grip.onpointerup=e=>{if(!dragging)return;dragging=false;const under=document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-frame]');row.classList.remove('dragging');if(under)move(i,Number(under.dataset.frame));};grip.onpointercancel=()=>{dragging=false;row.classList.remove('dragging');$('filmFrames').querySelectorAll('.drop-target').forEach(el=>el.classList.remove('drop-target'));};const controls=node('div','film-frame-controls'),seconds=node('input');seconds.type='number';seconds.min='1';seconds.max='60';seconds.step='1';seconds.value=String(f.seconds);seconds.setAttribute('aria-label',`第 ${i+1} 幕停留秒数`);seconds.onchange=()=>{f.seconds=Math.min(60,Math.max(1,Number(seconds.value)||4));seconds.value=String(f.seconds);keep();};controls.append(seconds,node('small','','秒'),button('↑',()=>move(i,i-1)),button('↓',()=>move(i,i+1)),button('删除',()=>{film.frames.splice(i,1);edit();keep();}));row.append(controls);row.ondragstart=e=>e.dataTransfer.setData('text/plain',String(i));row.ondragover=e=>e.preventDefault();row.ondrop=e=>{e.preventDefault();move(Number(e.dataTransfer.getData('text/plain')),i);};$('filmFrames').append(row);}if(!film.frames.length)$('filmFrames').append(node('p','daily-empty','从回忆墙选几段内容，装进这一卷。'));}
 function move(from,to){if(!Number.isInteger(from)||to<0||to>=film.frames.length||from<0||from>=film.frames.length)return;const [frame]=film.frames.splice(from,1);film.frames.splice(to,0,frame);edit();keep();}
 $('filmNew').onclick=()=>{stopPreview();film={id:randomId(),room_id:state.room,owner_user_id:state.userId,title:'我们的片段',frames:[],bgm:null};edit();keep();};$('filmTitle').oninput=keep;$('filmAdd').onclick=()=>void memories.select(film?.frames.map(f=>f.source)||[]);
 $('filmBgm').onchange=async()=>{const file=$('filmBgm').files[0],s=snap(),target=film;if(!file||!film)return;if(file.size>20*1024*1024){toast('背景音乐请控制在 20 MB 以内。');return;}if(!file.type.startsWith('audio/')){toast('请选择音频文件。');return;}try{$('filmSaveStatus').textContent='正在保存配乐…';const media=await upload(file,s,uploads);if(!current(s)||target!==film)return;film.bgm=media;edit();keep();$('filmSaveStatus').textContent='配乐已就绪。';}catch(e){if(current(s))$('filmSaveStatus').textContent=e.message;}};$('filmRemoveBgm').onclick=()=>{film.bgm=null;edit();keep();};
 $('filmSave').onclick=async()=>{if(!film)return;keep();const s=snap(),target=film,version=editing,payload=structuredClone(film);try{if(!film.title.trim()||!film.frames.length)throw new Error('请给胶片起个名字，并至少选一幕回忆。');$('filmSave').disabled=true;const saved=await db.saveFilm(payload);if(!current(s)||film!==target)return;if(version===editing){film=saved;storeSet(draftKey(),null);}else{film.revision=saved.revision;keep();}films=films.filter(f=>f.id!==saved.id).concat(saved);list();$('filmSaveStatus').textContent=version===editing?'胶片已保存。':'提交时的内容已保存，随后修改的草稿仍保留，请再次保存。';}catch(e){if(current(s))$('filmSaveStatus').textContent=e.message||'没有保存成功，本机草稿还在。';}finally{if(current(s))$('filmSave').disabled=false;}};
 async function begin(){if(!film?.frames.length){toast('先选几段回忆吧。');return;}sound.unlock();keep();const s=snap(),version=++generation,target=structuredClone(film);$('filmPreview').disabled=true;try{await memories.refresh();if(!current(s)||version!==generation)return;preview=[];for(const f of target.frames){const memory=await memories.resolve(f.source);if(!current(s)||version!==generation)return;if(memory)preview.push({...f,memory});}if(!preview.length)throw new Error('这些回忆已不可读取，请重新选择。');if(preview.length<film.frames.length)toast('已跳过无法读取的回忆，胶片草稿中仍保留原位置。');$('filmEditor').hidden=true;$('filmList').hidden=true;$('filmProjector').hidden=false;$('spacePages').scrollTop=0;$('filmProjector').classList.remove('paused','rewinding');index=0;frameElapsed=0;playing=true;rewinding=false;lastTime=performance.now();sound.setLevel($('filmSound').value);sound.start();$('filmPlay').textContent='暂停';timeline();await scene();if(!current(s)||version!==generation)return;if(bgmUrl){URL.revokeObjectURL(bgmUrl);bgmUrl='';}if(target.bgm){const blob=await mediaBlob(s.room,target.bgm.path);if(!current(s)||version!==generation)return;bgmUrl=URL.createObjectURL(blob);bgm.src=bgmUrl;bgm.volume=.6;await bgm.play().catch(()=>toast('点击播放后，背景音乐就能加入。'));}sound.duck(!bgm.paused||hasOriginalSound());cancelAnimationFrame(raf);raf=requestAnimationFrame(tick);revealControls();}catch(e){if(current(s)){$('filmStatus').textContent=e.message;stopPreview();}}finally{if(current(s))$('filmPreview').disabled=false;}}
 $('filmPreview').onclick=()=>void begin();
 function hasOriginalSound(){return [...$('filmScene').querySelectorAll('video,audio')].some(a=>!a.paused&&!a.muted);}
 async function scene(){const version=++sceneId,s=snap(),item=preview[index];if(!item)return;$('filmScene').querySelectorAll('video,audio').forEach(m=>m.pause());const content=node('div','film-frame');content.append(node('time','',item.memory.date));if(item.memory.media?.length)await memories.getMedia(item.memory,content,true);if(!current(s)||version!==sceneId)return;if(item.memory.title)content.append(node('h3','',item.memory.title));if(item.memory.body)content.append(node('p','film-text',item.memory.body));$('filmScene').replaceChildren(content);$('filmPosition').textContent=`${index+1} / ${preview.length}`;$('filmProjector').dataset.index=String(index);$('filmProgress').value=String(index);for(const b of $('filmTimeline').children)b.setAttribute('aria-current',String(Number(b.dataset.index)===index));for(const video of content.querySelectorAll('video,audio')){video.controls=false;video.muted=false;video.addEventListener('play',()=>sound.duck(true));video.addEventListener('pause',()=>sound.duck(!bgm.paused||hasOriginalSound()));video.playbackRate=Number($('filmSpeed').value);if(playing&&!rewinding)void video.play().catch(()=>{video.controls=true;});}sound.duck(!bgm.paused||hasOriginalSound());const gate=$('filmGate');gate.classList.remove('splicing');void gate.offsetWidth;gate.classList.add('splicing');content.style.setProperty('--scene-duration',item.seconds+'s');sound.click(rewinding?.65:1);}
 function timeline(){$('filmTotal').textContent=duration(preview.reduce((n,f)=>n+f.seconds,0));const list=$('filmTimeline');list.replaceChildren();$('filmProgress').max=String(Math.max(0,preview.length-1));for(const [i,item] of preview.entries()){const b=button('',()=>jump(i-index));b.className='film-timeline-frame';b.dataset.index=String(i);b.setAttribute('aria-label','跳到第 '+(i+1)+' 幕');if(item.memory.media?.length)void memories.getMedia(item.memory,b);else b.append(node('span','',(item.memory.title||item.memory.body).slice(0,24)));b.append(node('small','',String(i+1).padStart(2,'0')));list.append(b);}}
 $('filmProgress').oninput=()=>jump(Number($('filmProgress').value)-index);
 function tick(now){if($('filmProjector').hidden)return;const delta=Math.min(.2,(now-lastTime)/1000);lastTime=now;if(playing&&!rewinding){frameElapsed+=delta*Number($('filmSpeed').value);if(frameElapsed>=preview[index].seconds){if(index<preview.length-1){index++;frameElapsed=0;void scene();}else pause();}}$('filmElapsed').textContent=duration(preview.slice(0,index).reduce((n,f)=>n+f.seconds,0)+frameElapsed);if(now-grainTime>48){grainTime=now;grain();}raf=requestAnimationFrame(tick);}
 function grain(){const canvas=$('filmGrain'),c=canvas.getContext('2d',{alpha:true}),pixels=c.createImageData(canvas.width,canvas.height);for(let i=0;i<pixels.data.length;i+=4){const n=Math.random()*255;pixels.data[i]=pixels.data[i+1]=pixels.data[i+2]=n;pixels.data[i+3]=Math.random()*42;}c.putImageData(pixels,0,0);if(Math.random()<.13){c.fillStyle='#e5d7c566';c.fillRect(Math.random()*canvas.width,Math.random()*canvas.height,1,Math.random()*15+2);}$('filmGate').style.setProperty('--gate-x',(Math.random()-.5)*(rewinding?7:1)+'px');$('filmGate').style.setProperty('--gate-y',(Math.random()-.5)*(rewinding?13:1.5)+'px');}
 function pause(){playing=false;bgm.pause();$('filmScene').querySelectorAll('video,audio').forEach(m=>m.pause());$('filmPlay').textContent='播放';sound.stop();$('filmProjector').classList.add('paused');}
 async function play(){const s=snap(),version=generation;sound.unlock();endRewind();if(index===preview.length-1&&frameElapsed>=preview[index].seconds){index=0;frameElapsed=0;await scene();}if(!current(s)||version!==generation)return;playing=true;$('filmPlay').textContent='暂停';$('filmProjector').classList.remove('paused');sound.start();if(bgm.src)void bgm.play().catch(()=>{});$('filmScene').querySelectorAll('video,audio').forEach(m=>void m.play().catch(()=>{}));sound.duck(!bgm.paused||hasOriginalSound());}
 $('filmPlay').onclick=()=>playing?pause():void play();
 function jump(step){sound.unlock();endRewind();index=Math.max(0,Math.min(preview.length-1,index+step));frameElapsed=0;void scene();revealControls();} $('filmPrev').onclick=()=>jump(-1);$('filmNext').onclick=()=>jump(1);
 function startRewind(){if(!preview.length||$('filmProjector').hidden)return;sound.unlock();playing=false;rewinding=true;bgm.pause();$('filmScene').querySelectorAll('audio,video').forEach(a=>a.pause());$('filmProjector').classList.add('rewinding');$('filmPlay').textContent='播放';sound.rewind(true);const step=()=>{if(index>0){index--;frameElapsed=0;void scene();}else endRewind();};step();clearInterval(rewindTimer);if(rewinding)rewindTimer=setInterval(step,160);revealControls();}
 function endRewind(){clearInterval(rewindTimer);rewindTimer=0;if(!rewinding)return;rewinding=false;sound.rewind(false);sound.stop();$('filmProjector').classList.remove('rewinding');$('filmProjector').classList.add('paused');sound.click(.8);}
 const rewind=$('filmRewind');rewind.onpointerdown=e=>{rewind.setPointerCapture(e.pointerId);longHold=false;holdTimer=setTimeout(()=>{longHold=true;startRewind();},180);};rewind.onpointerup=()=>{clearTimeout(holdTimer);if(longHold)endRewind();};rewind.onpointercancel=()=>{clearTimeout(holdTimer);longHold=true;endRewind();};rewind.onclick=()=>{if(longHold){longHold=false;return;}rewinding?endRewind():startRewind();};
 $('filmSpeed').onchange=()=>{bgm.playbackRate=Number($('filmSpeed').value);$('filmScene').querySelectorAll('video,audio').forEach(m=>m.playbackRate=Number($('filmSpeed').value));};
 $('filmSound').onchange=()=>sound.setLevel($('filmSound').value);$('filmFullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await $('filmProjector').requestFullscreen();}catch{toast('这个浏览器暂时无法全屏，仍可在这里放映。');}};
 function revealControls(){$('filmControls').classList.remove('quiet');clearTimeout(controlTimer);controlTimer=setTimeout(()=>{if(playing&&!rewinding)$('filmControls').classList.add('quiet');},3200);} $('filmProjector').onpointermove=revealControls;$('filmGate').onclick=e=>{if(!e.target.closest('audio,video,button'))void showFrameDetail();};$('filmDetailOpen').onclick=()=>void showFrameDetail();$('filmProjector').onfocusin=revealControls;
 const duration=value=>Math.floor(value/60)+':'+String(Math.floor(value%60)).padStart(2,'0');
 async function showFrameDetail(){
  const item=preview[index];if(!item)return;endRewind();pause();cancelAnimationFrame(raf);const version=++sceneId,s=snap(),detail=$('filmDetail');if(document.fullscreenElement=== $('filmProjector'))await document.exitFullscreen().catch(()=>{});if(!current(s)||version!==sceneId)return;detail.replaceChildren();detail.hidden=false;$('filmProjector').hidden=true;
  detail.append(button('‹ 继续看这一幕',()=>{detail.querySelectorAll('audio,video').forEach(m=>m.pause());detail.replaceChildren();detail.hidden=true;$('filmProjector').hidden=false;lastTime=performance.now();raf=requestAnimationFrame(tick);}),node('h3','',item.memory.title||'回忆详情'),node('time','',item.memory.date));
  await memories.getMedia(item.memory,detail,true);if(!current(s)||version!==sceneId)return;
  detail.append(node('p','memory-full-text',item.memory.body),node('small','memory-tags',(item.memory.tags||[]).map(t=>'#'+t).join(' ')));if(item.memory.back)detail.append(node('p','memory-full-text',item.memory.back));const foot=node('footer');foot.innerHTML=poetryMarkup(9);detail.append(foot);applyPoetry(foot);$('spacePages').scrollTop=0;
 }
 function stopPreview(){$('filmDetail').hidden=true;$('filmDetail').querySelectorAll('audio,video').forEach(m=>m.pause());$('filmDetail').replaceChildren();generation++;sceneId++;clearTimeout(holdTimer);clearTimeout(controlTimer);cancelAnimationFrame(raf);endRewind();pause();$('filmScene').replaceChildren();$('filmTimeline').replaceChildren();$('filmProjector').hidden=true;$('filmProjector').classList.remove('paused','rewinding');$('filmList').hidden=false;$('filmEditor').hidden=!film;bgm.removeAttribute('src');bgm.load();if(bgmUrl){URL.revokeObjectURL(bgmUrl);bgmUrl='';}if(document.fullscreenElement===$('filmProjector'))void document.exitFullscreen();}
 $('filmExit').onclick=stopPreview;document.addEventListener('mailbox:space-close',stopPreview);document.addEventListener('mailbox:space-page',()=>{if(state.spacePanel!=='filmSpace')stopPreview();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&!$('filmProjector').hidden){endRewind();pause();}});window.addEventListener('pagehide',()=>{keep();sound.close();});
 function reset(){epoch++;stopPreview();sound.close();film=null;films=[];preview=[];$('filmEditor').hidden=true;$('filmList').replaceChildren();$('filmBgm').value='';$('filmSaveStatus').textContent='';$('filmStatus').textContent='';}
 return {reset,open};
}
