// Synthesized mechanical layers; starts only after a playback/control gesture.
export function createFilmAudio(){
 let ctx,master,motor,noise,hum,pulse,modulation,level='light',ducked=false,rewinding=false,playing=false;
 function init(){if(!ctx){const Audio=window.AudioContext||window.webkitAudioContext;if(!Audio)return;ctx=new Audio();master=ctx.createGain();master.gain.value=0;master.connect(ctx.destination);motor=ctx.createGain();motor.gain.value=0;motor.connect(master);const buffer=ctx.createBuffer(1,ctx.sampleRate,ctx.sampleRate),samples=buffer.getChannelData(0);for(let i=0;i<samples.length;i++)samples[i]=(Math.random()*2-1)*.16;noise=ctx.createBufferSource();noise.buffer=buffer;noise.loop=true;const filter=ctx.createBiquadFilter();filter.type='bandpass';filter.frequency.value=750;filter.Q.value=.7;noise.connect(filter);filter.connect(motor);noise.start();hum=ctx.createOscillator();hum.type='triangle';hum.frequency.value=48;const g=ctx.createGain();g.gain.value=.025;hum.connect(g);g.connect(motor);hum.start();pulse=ctx.createOscillator();pulse.frequency.value=18;pulse.type='sine';modulation=ctx.createGain();modulation.gain.value=0;pulse.connect(modulation);modulation.connect(motor.gain);pulse.start();}void ctx.resume();volume();}
 function volume(){if(!ctx)return;modulation.gain.setTargetAtTime(playing||rewinding?(ducked?.009:.06):0,ctx.currentTime,.03);master.gain.setTargetAtTime(level==='off'?0:level==='immersive'?.6:.22,ctx.currentTime,.08);motor.gain.setTargetAtTime(playing||rewinding?(ducked?.07:rewinding?.75:.3):0,ctx.currentTime,.06);}
 function click(strength=1){init();if(!ctx||level==='off')return;const source=ctx.createBufferSource(),b=ctx.createBuffer(1,Math.ceil(ctx.sampleRate*.035),ctx.sampleRate),d=b.getChannelData(0);for(let i=0;i<d.length;i++)d[i]=(Math.random()*2-1)*Math.exp(-i/(d.length*.17))*.2*strength;source.buffer=b;const filter=ctx.createBiquadFilter();filter.type='lowpass';filter.frequency.value=1600;source.connect(filter);filter.connect(master);source.start();source.onended=()=>{source.disconnect();filter.disconnect();};}
 function mechanical(start){init();if(!ctx)return;click(start?.8:1.2);const oscillator=ctx.createOscillator(),gain=ctx.createGain(),t=ctx.currentTime;oscillator.type='triangle';oscillator.frequency.setValueAtTime(start?35:105,t);oscillator.frequency.exponentialRampToValueAtTime(start?105:28,t+.3);gain.gain.setValueAtTime(.055,t);gain.gain.exponentialRampToValueAtTime(.001,t+.35);oscillator.connect(gain);gain.connect(master);oscillator.start();oscillator.stop(t+.36);oscillator.onended=()=>{oscillator.disconnect();gain.disconnect();};}
 return {unlock:init,start(){init();playing=true;mechanical(true);volume();},stop(){playing=false;rewinding=false;if(ctx){mechanical(false);noise.playbackRate.setTargetAtTime(1,ctx.currentTime,.08);hum.frequency.setTargetAtTime(48,ctx.currentTime,.1);}volume();},click,rewind(on){init();rewinding=on;if(ctx){noise.playbackRate.setTargetAtTime(on?2.8:1,ctx.currentTime,.07);hum.frequency.setTargetAtTime(on?170:48,ctx.currentTime,.07);pulse.frequency.setTargetAtTime(on?45:18,ctx.currentTime,.07);}volume();},setLevel(value){level=value;volume();},duck(value){ducked=value;volume();},close(){playing=false;rewinding=false;if(ctx){void ctx.close();ctx=null;}}};
}
