import {localDate,randomId,storeGet,storeSet} from './core.js?v=2.4.2';
import {allMessages,events,mediaBlob} from './feature-backend.js?v=2.4.2';
import * as daily from './daily-backend.js?v=2.4.2';
import * as db from './memory-backend.js?v=2.4.2';
import {memoryCollection,memoryLinks,todaySummary,discIndex} from './memory-core.js?v=2.4.2';

export function initMemorySpace({$,state,node,toast,notice,ui,isHidden=()=>false}){
 const pane=$('wallSpace'),box=$('wallEntries');box.className='memory-viewport';
 const chrome=node('div','memory-tools');chrome.innerHTML='<div class="memory-modes"><button data-memory-mode="notes">便签墙</button><button data-memory-mode="board">线索板</button><button data-memory-mode="disc">唱片墙</button><button id="memoryAdd" aria-label="写一张便签">＋</button></div><div class="memory-filters"><input id="memoryDate" type="date" aria-label="按日期筛选回忆"/><input id="memoryTag" placeholder="日期之外，也可找标签" aria-label="按标签筛选回忆"/><button id="memoryClear">全部</button></div><div class="memory-options"><button id="memoryLight">关灯</button><label><input id="memorySummary" type="checkbox" checked/>每日小结</label><button id="memorySelect">选择</button></div><div id="memorySelection" hidden><span id="memorySelectedCount"></span><button id="memorySelectAll">全选</button><button id="memoryFilmAdd">加入胶片</button></div><p id="memoryStatus" role="status"></p>';
 pane.prepend(chrome);const editor=node('div','memory-editor');editor.id='memoryEditor';editor.hidden=true;chrome.after(editor);
 const detail=node('section','memory-detail');detail.id='memoryDetail';detail.hidden=true;box.after(detail);
 let history=[],entries=[],calendar=[],listens=[],profile={data:{},revision:0},rows=[],reading=null,epoch=0,selected=new Set(),selecting=false,mode='notes',dark=false,visibleLimit=36,angle=0,inertia=0,stop=null,saves=Promise.resolve(),filmOpen=null;
 const urls=new Map(),uploads=new WeakMap(),snap=()=>({room:state.room,userId:state.userId,epoch:state.epoch,localEpoch:epoch});
 const current=s=>s.room===state.room&&s.userId===state.userId&&s.epoch===state.epoch&&s.localEpoch===epoch;
 const draftKey=(s=snap())=>`memory-draft.${s.room}.${s.userId}`;
 function button(text,fn,cls='text-btn'){const b=node('button',cls,text);b.type='button';b.onclick=fn;return b;}
 function err(e){return ['42P01','PGRST205'].includes(e.code)?'回忆资料暂时无法同步，请完成房间数据更新后重试。':e.message||'没有保存成功，请稍后重试。';}
 function collection(){const messages=[...new Map([...history,...state.messages].filter(m=>!isHidden(m.id)).map(m=>[m.id,m])).values()];rows=memoryCollection({messages,entries,events:calendar,listens,profile});if(profile.data.summary!==false){const summary=todaySummary(rows);if(summary)rows.unshift(summary);}return rows;}
 async function refresh(){if(!state.ready)return;if(reading)return reading;const s=snap();const work=(async()=>{try{const result=await Promise.all([allMessages(s.room,state.secure,()=>{},()=>!current(s)),state.secure?daily.listRows('space_entries',s.room):[],state.secure?events(s.room):[],state.secure?db.readProfile(s.room,s.userId):null,state.secure?daily.rpc('mailbox_listen_report',{p_room:s.room,p_start:localDate(new Date(Date.now()-364*86400000)),p_end:localDate()}):{daily:[]}]);if(!current(s))return;[history,entries,calendar]=result;profile=result[3]||{room_id:s.room,owner_user_id:s.userId,data:{},revision:0};listens=result[4].daily;const draft=storeGet(draftKey(s),null);if(draft&&draft.revision===profile.revision){profile.data=draft.data;$('memoryStatus').replaceChildren(document.createTextNode('上次未同步的调整已恢复。'),button('重试保存',()=>void save()));}else $('memoryStatus').textContent='';mode=['notes','board','disc'].includes(profile.data.view)?profile.data.view:'notes';angle=Number(profile.data.angle)||0;$('memorySummary').checked=profile.data.summary!==false;render();}catch(e){if(current(s)){$('memoryStatus').textContent=err(e);render();}}finally{if(current(s))reading=null;}})();reading=work;return work;}
 function save(){const s=snap(),data=structuredClone(profile.data);storeSet(draftKey(s),{data,revision:profile.revision});if(!state.secure)return Promise.resolve();const work=saves.catch(()=>{}).then(async()=>{if(!current(s))return;try{const saved=await db.saveProfile({room_id:s.room,owner_user_id:s.userId,data,revision:profile.revision});if(!current(s))return;profile.revision=saved.revision;const pending=storeGet(draftKey(s),null);if(JSON.stringify(pending?.data)===JSON.stringify(data)){storeSet(draftKey(s),null);$('memoryStatus').textContent='';}else if(pending)storeSet(draftKey(s),{...pending,revision:saved.revision});}catch(e){if(current(s)){$('memoryStatus').replaceChildren(document.createTextNode(err(e)),button('重试保存',()=>void save()));}}});saves=work;return work;}
 async function media(memory,host,full=false){const s=snap();for(const item of memory.media||[]){const type=item.type||item.mime?.split('/')[0];if(!['image','video','audio'].includes(type))continue;const element=node(type==='image'?'img':type,'memory-media');if(type==='image'){element.alt=item.name||memory.title||'回忆照片';element.loading='lazy';}else{element.controls=full;element.preload='metadata';element.muted=!full;}host.append(element);try{let url=urls.get(item.path);if(!url){const blob=await mediaBlob(s.room,item.path);if(!current(s))return;url=URL.createObjectURL(blob);urls.set(item.path,url);}if(current(s))element.src=url;}catch{element.replaceWith(node('small','',item.name||'附件暂时无法打开'));}}}
 function card(memory,index=0){const el=node('article','memory-card'+(memory.id.startsWith('message:')?' msg':'')+(memory.kind==='anniversary'?' wall-event':'')+(memory.media?.length?' has-photo':''));el.tabIndex=0;el.dataset.memoryId=memory.id;el.dataset.kind=memory.kind;el.style.setProperty('--paper-index',index%5);el.style.setProperty('--tilt',((index%5)-2)*.7+'deg');el.setAttribute('aria-label',(memory.title||memory.body).slice(0,80));if(selecting){const select=node('input');select.type='checkbox';select.checked=selected.has(memory.id);select.setAttribute('aria-label','选择回忆');select.onchange=()=>{select.checked?selected.add(memory.id):selected.delete(memory.id);selection();};el.append(select);}const front=node('div','memory-card-front');if(memory.media?.length)void media(memory,front);if(memory.title)front.append(node('h4','',memory.title));front.append(node('p','',memory.body.slice(0,220)),node('time','',memory.date));const back=node('div','memory-card-back');back.append(node('p','',memory.back||'翻过这一页，写下当时没有说完的话。'),node('small','',(memory.tags||[]).map(t=>'#'+t).join(' ')));el.append(front,back);const actions=node('div','memory-card-actions');actions.append(button('翻面',e=>{el.classList.toggle('flipped');}),button('详情',()=>showDetail(memory)));el.append(actions);el.ondblclick=()=>showDetail(memory);el.onkeydown=e=>{if(e.key==='Enter')showDetail(memory);};el.onclick=e=>{if(!e.target.closest('button,input')){focus(el);if(selecting){selected.has(memory.id)?selected.delete(memory.id):selected.add(memory.id);el.querySelector('input').checked=selected.has(memory.id);selection();}}};return el;}
 function focus(element){const stage=element.closest('.memory-stage');if(!stage)return;const r=stage.getBoundingClientRect(),b=element.getBoundingClientRect();stage.style.setProperty('--light-x',b.x+b.width/2-r.x+stage.scrollLeft+'px');stage.style.setProperty('--light-y',b.y+b.height/2-r.y+stage.scrollTop+'px');}
 function light(stage){stage.classList.toggle('dark',dark);const shade=node('div','memory-shade');stage.append(shade);let raf=0,last=null;stage.addEventListener('pointermove',e=>{if(!dark)return;const r=stage.getBoundingClientRect();last={x:e.clientX-r.x+stage.scrollLeft,y:e.clientY-r.y+stage.scrollTop};if(!raf)raf=requestAnimationFrame(()=>{stage.style.setProperty('--light-x',last.x+'px');stage.style.setProperty('--light-y',last.y+'px');raf=0;});});stage.addEventListener('pointerdown',e=>{if(!dark||e.target.closest('button,input,audio,video'))return;stage.setPointerCapture(e.pointerId);const target=e.target.closest('.memory-card');if(target)focus(target);else{const r=stage.getBoundingClientRect();stage.style.setProperty('--light-x',e.clientX-r.x+stage.scrollLeft+'px');stage.style.setProperty('--light-y',e.clientY-r.y+stage.scrollTop+'px');}});}
 function render(){collection();if(pane.hidden)return;cancelAnimationFrame(inertia);const filtered=rows.filter(r=>(!$('memoryDate').value||r.date===$('memoryDate').value)&&(!$('memoryTag').value||(r.tags||[]).some(t=>t.includes($('memoryTag').value))||r.title?.includes($('memoryTag').value)));for(const b of chrome.querySelectorAll('[data-memory-mode]'))b.classList.toggle('active',b.dataset.memoryMode===mode);box.replaceChildren();box.dataset.mode=mode;const stage=node('div','memory-stage '+(mode==='board'?'clue-stage':mode==='disc'?'disc-stage':'note-stage'));box.append(stage);if(!filtered.length)stage.append(node('p','daily-empty','还没有符合条件的回忆。写张便签，留住今天吧。'));else if(mode==='disc')disc(stage,filtered);else if(mode==='board')board(stage,filtered.slice(0,visibleLimit));else{const grid=node('div','memory-note-grid');filtered.slice(0,visibleLimit).forEach((r,i)=>grid.append(card(r,i)));stage.append(grid);if(filtered.length>visibleLimit)stage.append(button('再看看更早的回忆',()=>{visibleLimit+=36;render();}));}if(mode==='board'&&filtered.length>visibleLimit)box.append(button('把更早的回忆也放到板上',()=>{visibleLimit+=36;render();}));light(stage);$('memoryLight').textContent=dark?'开灯':'关灯';selection();}
 function board(stage,visible){const canvas=node('div','clue-canvas');canvas.style.height=Math.max(850,Math.ceil(visible.length/3)*230+100)+'px';stage.style.setProperty('--board-height',canvas.style.height);stage.append(canvas);const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.classList.add('clue-lines');canvas.append(svg);const positions=new Map(),elements=new Map();for(const [i,m] of visible.entries()){const saved=profile.data.positions?.[m.id],pos={x:Math.max(10,Math.min(840,Number(saved?.x)||22+(i%3)*175)),y:Math.max(10,Math.min(9000,Number(saved?.y)||40+Math.floor(i/3)*220+(i%2)*15))};positions.set(m.id,pos);const el=card(m,i);el.style.left=pos.x+'px';el.style.top=pos.y+'px';canvas.append(el);elements.set(m.id,el);let drag=null;el.addEventListener('pointerdown',e=>{if(dark||e.target.closest('button,input'))return;el.setPointerCapture(e.pointerId);drag={x:e.clientX,y:e.clientY,px:pos.x,py:pos.y,moved:false};});el.addEventListener('pointermove',e=>{if(!drag)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;if(Math.abs(dx)+Math.abs(dy)>4)drag.moved=true;if(!drag.moved)return;e.preventDefault();pos.x=Math.max(10,Math.min(840,drag.px+dx));pos.y=Math.max(10,Math.min(canvas.offsetHeight-220,drag.py+dy));el.style.left=pos.x+'px';el.style.top=pos.y+'px';draw();});const end=()=>{if(drag?.moved){profile.data.positions={...profile.data.positions,[m.id]:pos};void save();}drag=null;};el.addEventListener('pointerup',end);el.addEventListener('pointercancel',end);}
  function draw(){svg.replaceChildren();for(const link of memoryLinks(visible,profile.data.links||[])){const a=positions.get(link.from),b=positions.get(link.to);if(!a||!b)continue;const line=document.createElementNS(svg.namespaceURI,'line');line.setAttribute('x1',a.x+75);line.setAttribute('y1',a.y+4);line.setAttribute('x2',b.x+75);line.setAttribute('y2',b.y+4);const title=document.createElementNS(svg.namespaceURI,'title');title.textContent=link.label;line.append(title);line.dataset.relation=link.label;svg.append(line);}}draw();
 }
 function discCard(memory,index){const el=node('article','record-memory'+(memory.media?.length?' has-photo':'')+(memory.id.startsWith('message:')?' msg':''));el.dataset.memoryId=memory.id;el.dataset.kind=memory.kind;if(selecting){const c=node('input');c.type='checkbox';c.checked=selected.has(memory.id);c.setAttribute('aria-label','选择回忆');c.onchange=()=>{c.checked?selected.add(memory.id):selected.delete(memory.id);selection();};el.append(c);}void media(memory,el);el.append(node('time','',memory.date),node('h4','',memory.title||({music:'同一段旋律',anniversary:'记得这一天',diary:'日记里的一页'})[memory.kind]||'时光片段'),node('p','',memory.body.slice(0,index?65:150)),button('展开 ›',()=>showDetail(memory)));el.ondblclick=()=>showDetail(memory);return el;}
 function disc(stage,items){cancelAnimationFrame(inertia);const record=node('div','memory-disc');record.tabIndex=0;record.setAttribute('role','slider');record.setAttribute('aria-label','转动唱片浏览回忆');record.setAttribute('aria-valuemin','1');record.setAttribute('aria-valuemax',String(items.length));record.append(node('span','memory-disc-label','OUR DAYS'));stage.append(record);const memories=node('div','disc-memories');stage.append(memories);let lastIndex=-1,drag=null,velocity=0;const position=()=>{record.style.setProperty('--disc-angle',angle+'deg');const i=discIndex(angle,items.length);record.setAttribute('aria-valuenow',String(i+1));if(i!==lastIndex){lastIndex=i;memories.replaceChildren(...[0,1,2].slice(0,items.length).map((n)=>discCard(items[(i+n)%items.length],n)));}};position();record.onpointerdown=e=>{cancelAnimationFrame(inertia);record.setPointerCapture(e.pointerId);drag={x:e.clientX,y:e.clientY,t:performance.now()};velocity=0;};record.onpointermove=e=>{if(!drag)return;const now=performance.now(),dx=e.clientX-drag.x,dy=e.clientY-drag.y,delta=(Math.abs(dx)>Math.abs(dy)?-dx:dy)*.55;angle+=delta;velocity=delta/Math.max(10,now-drag.t)*16;drag={x:e.clientX,y:e.clientY,t:now};position();};const release=()=>{if(!drag)return;drag=null;const tick=()=>{angle+=velocity;velocity*=.94;position();if(Math.abs(velocity)>.12)inertia=requestAnimationFrame(tick);else{profile.data.angle=angle;void save();}};tick();};record.onpointerup=release;record.onpointercancel=release;record.onkeydown=e=>{if(['ArrowDown','ArrowUp','ArrowRight','ArrowLeft'].includes(e.key)){e.preventDefault();angle+=['ArrowDown','ArrowRight'].includes(e.key)?30:-30;position();profile.data.angle=angle;void save();}};stage.append(node('small','disc-hint','滑动唱片 · 遇见另一段时光'));
 }
 function selection(){ $('memorySelection').hidden=!selecting;$('memorySelectedCount').textContent=`已选 ${selected.size} 条`;$('memoryFilmAdd').disabled=!selected.size||!filmOpen;$('memorySelect').textContent=selecting?'完成选择':'选择';}
 $('memorySelect').onclick=()=>{selecting=!selecting;render();};$('memorySelectAll').onclick=()=>{rows.filter(r=>(!$('memoryDate').value||r.date===$('memoryDate').value)&&(!$('memoryTag').value||(r.tags||[]).some(t=>t.includes($('memoryTag').value)))).forEach(r=>selected.add(r.id));render();};$('memoryFilmAdd').onclick=()=>filmOpen?.([...selected]);
 chrome.querySelectorAll('[data-memory-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.memoryMode;profile.data.view=mode;void save();render();});$('memoryLight').onclick=()=>{dark=!dark;box.querySelector('.memory-stage')?.classList.toggle('dark',dark);$('memoryLight').textContent=dark?'开灯':'关灯';};$('memorySummary').onchange=()=>{profile.data.summary=$('memorySummary').checked;void save();render();};for(const id of ['memoryDate','memoryTag'])$(id).oninput=render;$('memoryClear').onclick=()=>{$('memoryDate').value='';$('memoryTag').value='';render();};
 function showDetail(memory){box.hidden=true;detail.hidden=false;detail.replaceChildren();const head=node('div','memory-detail-head');head.append(button('‹ 回到墙上',()=>{detail.hidden=true;box.hidden=false;}),button('补充记录',()=>annotate(memory)));detail.append(head,node('time','',memory.date),node('h3','',memory.title||'记得这一刻'));void media(memory,detail,true);detail.append(node('p','memory-full-text',memory.body));if(memory.private)detail.append(node('small','','仅自己可见'));const back=node('div','memory-back-copy');back.hidden=true;back.append(node('p','memory-full-text',memory.back||'这里还没有背面的文字。'),node('p','',(memory.tags||[]).map(t=>'#'+t).join(' ')));detail.append(button('翻到背面',()=>back.hidden=!back.hidden),back);if(filmOpen)detail.append(button('加入胶片',()=>filmOpen([memory.id])));const links=memoryLinks(rows,profile.data.links||[]).filter(l=>l.from===memory.id||l.to===memory.id);for(const l of links){const other=rows.find(r=>r.id===(l.from===memory.id?l.to:l.from));if(other)detail.append(button(`${l.label} · ${(other.title||other.body).slice(0,35)}`,()=>showDetail(other)));}const select=node('select');select.setAttribute('aria-label','关联另一条回忆');select.append(Object.assign(node('option','','关联另一条回忆'),{value:''}),...rows.filter(r=>r.id!==memory.id).map(r=>Object.assign(node('option','',`${r.date} ${(r.title||r.body).slice(0,22)}`),{value:r.id})));detail.append(select,button('连上线索',()=>{if(!select.value)return;profile.data.links=[...(profile.data.links||[]),{from:memory.id,to:select.value,label:'主动关联'}];void save();showDetail(memory);}));}
 function field(form,key,label,value='',type='text'){const l=node('label','field'),el=node(type==='textarea'?'textarea':'input');if(type!=='textarea')el.type=type;else el.rows=4;el.name=key;el.value=value||'';el.setAttribute('aria-label',label);el.maxLength=type==='textarea'?20000:120;l.append(node('span','',label),el);form.insertBefore(l,form.querySelector('[type=submit]'));return el;}
 function form(title,save){editor.hidden=false;editor.replaceChildren();const f=node('form','daily-form');f.append(node('h4','',title));const b=node('button','btn primary','保存');b.type='submit';f.append(button('取消',()=>editor.hidden=true));editor.append(f);f.onsubmit=async e=>{e.preventDefault();b.disabled=true;const s=snap();try{await save(f,s);if(current(s)){editor.hidden=true;detail.hidden=true;box.hidden=false;render();}}catch(e){if(current(s))toast(err(e));}finally{b.disabled=false;}};f.append(b);return f;}
 function annotate(memory){const f=form('把线索记清楚',async f=>{const parts=key=>f.elements[key].value.split(/[,，、]/).map(t=>t.trim()).filter(Boolean);profile.data.annotations={...profile.data.annotations,[memory.id]:{back:f.elements.back.value,tags:parts('tags'),location:f.elements.location.value,people:parts('people'),event:f.elements.event.value}};await save();});for(const [key,label,type,value] of [['back','背面的文字','textarea',memory.back],['tags','标签（逗号分隔）','text',(memory.tags||[]).join('，')],['location','地点','text',memory.location],['people','人物（逗号分隔）','text',(memory.people||[]).join('，')],['event','同一事件的名字','text',memory.event]])field(f,key,label,value,type);}
 $('memoryAdd').onclick=()=>{if(!state.secure){toast('请在邀请房间里留下新便签。');return;}const id=randomId();const f=form('留下一个瞬间',async(f,s)=>{const files=[...f.elements.media.files];if(files.length>8)throw new Error('一张便签最多放 8 个附件。');const media=[];for(const file of files){media.push(await daily.upload(file,s,uploads));if(!current(s))return;}await daily.saveEntry({id,room_id:s.room,owner_user_id:s.userId,kind:'memory',visibility:f.elements.private.checked?'private':'shared',title:f.elements.title.value,body:f.elements.body.value,event_date:f.elements.date.value,data:{media,tags:f.elements.tags.value.split(/[,，、]/).map(t=>t.trim()).filter(Boolean)}});if(current(s))await refresh();});field(f,'title','标题');field(f,'body','想留下的话','','textarea');field(f,'date','日期',localDate(),'date').required=true;field(f,'tags','标签');const file=field(f,'media','图片、视频、音频','','file');file.multiple=true;file.accept='image/*,video/*,audio/*';const privateBox=field(f,'private','仅自己可见','','checkbox');privateBox.checked=false;};
 document.addEventListener('mailbox:space-open',()=>{if(state.spacePanel==='wallSpace'){render();void refresh();}});const suspend=()=>{cancelAnimationFrame(inertia);detail.querySelectorAll('audio,video').forEach(el=>el.pause());};document.addEventListener('mailbox:space-close',suspend);document.addEventListener('mailbox:space-page',()=>{if(pane.hidden)suspend();});
 function ready(){if(state.secure){const s=snap();stop=daily.watch(s.room,()=>{if(current(s)&&!pane.hidden)void refresh();});}}
 function reset(){epoch++;stop?.();stop=null;cancelAnimationFrame(inertia);for(const url of urls.values())URL.revokeObjectURL(url);urls.clear();history=[];entries=[];calendar=[];listens=[];profile={data:{},revision:0};rows=[];reading=null;saves=Promise.resolve();selected.clear();mode='notes';dark=false;selecting=false;angle=0;box.replaceChildren();detail.replaceChildren();detail.hidden=true;box.hidden=false;editor.hidden=true;$('memoryDate').value='';$('memoryTag').value='';}
 async function resolve(id){collection();const existing=rows.find(r=>r.id===id);if(existing)return existing;if(id.startsWith('summary:'))return todaySummary(rows,id.slice(8));if(id.startsWith('music:')&&state.secure){const day=id.slice(6),s=snap(),report=await daily.rpc('mailbox_listen_report',{p_room:s.room,p_start:day,p_end:day});if(!current(s))return null;return memoryCollection({listens:report.daily}).find(r=>r.id===id);}return null;}
 return {ready,reset,render,refresh,resolve,get rows(){return collection();},getMedia:media,onFilm(fn){filmOpen=fn;selection();},async select(ids){selected=new Set(ids);selecting=true;ui.openFeature('wallSpace');await refresh();render();}};
}
