import {createMemoryViewport,memoryLayout} from './memory-viewport.js?v=2.7.6';
import {applyPoetry,poetryMarkup} from './poetry.js?v=2.7.6';
import {localDate,randomId,storeGet,storeSet} from './core.js?v=2.7.6';
import {allMessages,events,mediaBlob} from './feature-backend.js?v=2.7.6';
import * as daily from './daily-backend.js?v=2.7.6';
import * as db from './memory-backend.js?v=2.7.6';
import {memoryCollection,memoryLinks,todaySummary,discIndex} from './memory-core.js?v=2.7.6';

export function initMemorySpace({$,state,node,toast,notice,ui,isHidden=()=>false}){
 const pane=$('wallSpace'),box=$('wallEntries');box.className='memory-viewport';
 const chrome=node('div','memory-tools');chrome.innerHTML='<div class="memory-modes"><button data-memory-mode="notes">便签墙</button><button data-memory-mode="board">线索板</button><button data-memory-mode="disc">唱片回忆</button><button id="memorySearchToggle" aria-label="搜索和筛选回忆" aria-expanded="false">⌕</button><button id="memoryAdd" aria-label="写一张便签">＋</button></div><div class="memory-kind-filters" aria-label="回忆类型"><button data-memory-kind="all" aria-pressed="true">全部</button><button data-memory-kind="image">照片</button><button data-memory-kind="text">便签</button><button data-memory-kind="diary">日记</button><button data-memory-kind="music">歌曲</button><button data-memory-kind="anniversary">日期</button></div><div class="memory-filters" id="memoryFilters" hidden><input id="memoryDate" type="date" aria-label="按日期筛选回忆"/><input id="memoryTag" placeholder="标签、标题或文字" aria-label="按标签筛选回忆"/><button id="memoryClear">全部</button></div><div class="memory-options"><label><input id="memorySummary" type="checkbox" checked/>每日小结</label><button id="memorySelect">多选</button></div><div id="memorySelection" hidden><span id="memorySelectedCount"></span><button id="memorySelectAll">全选</button><button id="memoryFilmAdd">加入胶片 →</button></div><p id="memoryStatus" role="status"></p>';
 chrome.id='memoryTools';chrome.hidden=true;chrome.setAttribute('role','region');chrome.setAttribute('aria-label','回忆工具');
 const toolsHead=node('div','memory-tools-head');toolsHead.append(node('b','','回忆工具'),button('×',()=>tools(false,true),'memory-tools-close'));toolsHead.lastChild.setAttribute('aria-label','收起回忆工具');chrome.prepend(toolsHead);
 const toolsToggle=button('整理',()=>tools(chrome.hidden),'memory-tools-toggle');toolsToggle.id='memoryToolsToggle';toolsToggle.hidden=true;toolsToggle.setAttribute('aria-controls','memoryTools');toolsToggle.setAttribute('aria-expanded','false');toolsToggle.setAttribute('aria-label','整理回忆：切换视图与筛选');$('relationClose').before(toolsToggle);
 function tools(open,restore=false){chrome.hidden=!open;toolsToggle.setAttribute('aria-expanded',String(open));if(restore)toolsToggle.focus({preventScroll:true});}
 const syncTools=()=>{toolsToggle.hidden=pane.hidden||$('relationSpace').inert;if(toolsToggle.hidden)tools(false);};
 document.addEventListener('mailbox:navigation',()=>tools(false));
 for(const event of ['mailbox:space-page','mailbox:space-open','mailbox:space-close'])document.addEventListener(event,syncTools);
 document.addEventListener('pointerdown',e=>{if(!chrome.hidden&&!chrome.contains(e.target)&&!toolsToggle.contains(e.target))tools(false);},true);
 document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!chrome.hidden){tools(false,true);e.preventDefault();e.stopImmediatePropagation();}},true);
 pane.prepend(chrome);pane.append($('memorySelection'),$('memoryStatus'));const editor=node('div','memory-editor');editor.id='memoryEditor';editor.hidden=true;chrome.after(editor);
 const detail=node('section','memory-detail');detail.id='memoryDetail';detail.hidden=true;box.after(detail);
 let history=[],entries=[],calendar=[],listens=[],profile={data:{},revision:0},rows=[],reading=null,epoch=0,selected=new Set(),selecting=false,mode='notes',dark=false,visibleLimit=36,angle=0,inertia=0,stop=null,saves=Promise.resolve(),filmOpen=null;
 let renderKey='',lastRefreshAt=0;
 let viewport=null,kind='all',viewStates={},lastTap=null,lastWidth=0,lastHeight=0,resizeFrame=0,lightPercent=34;
 const opticsKey=()=>`memory-optics.${state.userId||'guest'}`;
 const urls=new Map(),uploads=new WeakMap(),snap=()=>({room:state.room,userId:state.userId,epoch:state.epoch,localEpoch:epoch});
 const current=s=>s.room===state.room&&s.userId===state.userId&&s.epoch===state.epoch&&s.localEpoch===epoch;
 const draftKey=(s=snap())=>`memory-draft.${s.room}.${s.userId}`;
 function button(text,fn,cls='text-btn'){const b=node('button',cls,text);b.type='button';b.onclick=fn;return b;}
 function err(e){return ['42P01','PGRST205'].includes(e.code)?'回忆资料暂时无法同步，请完成房间数据更新后重试。':e.message||'没有保存成功，请稍后重试。';}
 function collection(){const messages=[...new Map([...history,...state.messages].filter(m=>!isHidden(m.id)).map(m=>[m.id,m])).values()];rows=memoryCollection({messages,entries,events:calendar,listens,profile});if(profile.data.summary!==false){const summary=todaySummary(rows);if(summary)rows.unshift(summary);}return rows;}
 async function refresh(){if(!state.ready)return;if(reading)return reading;const s=snap();const work=(async()=>{try{const result=await Promise.all([allMessages(s.room,state.secure,()=>{},()=>!current(s)),state.secure?daily.listRows('space_entries',s.room):[],state.secure?events(s.room):[],state.secure?db.readProfile(s.room,s.userId):null,state.secure?daily.rpc('mailbox_listen_report',{p_room:s.room,p_start:localDate(new Date(Date.now()-364*86400000)),p_end:localDate()}):{daily:[]}]);if(!current(s))return;lastRefreshAt=Date.now();[history,entries,calendar]=result;profile=result[3]||{room_id:s.room,owner_user_id:s.userId,data:{},revision:0};listens=result[4].daily;const draft=storeGet(draftKey(s),null);if(draft&&draft.revision===profile.revision){profile.data=draft.data;$('memoryStatus').replaceChildren(document.createTextNode('上次未同步的调整已恢复。'),button('重试保存',()=>void save()));}else $('memoryStatus').textContent='';mode=['notes','board','disc'].includes(profile.data.view)?profile.data.view:'notes';angle=Number(profile.data.angle)||0;$('memorySummary').checked=profile.data.summary!==false;render();}catch(e){if(current(s)){$('memoryStatus').textContent=err(e);render();}}finally{if(current(s))reading=null;}})();reading=work;return work;}
 function save(){const s=snap(),data=structuredClone(profile.data);storeSet(draftKey(s),{data,revision:profile.revision});if(!state.secure)return Promise.resolve();const work=saves.catch(()=>{}).then(async()=>{if(!current(s))return;try{const saved=await db.saveProfile({room_id:s.room,owner_user_id:s.userId,data,revision:profile.revision});if(!current(s))return;profile.revision=saved.revision;const pending=storeGet(draftKey(s),null);if(JSON.stringify(pending?.data)===JSON.stringify(data)){storeSet(draftKey(s),null);$('memoryStatus').textContent='';}else if(pending)storeSet(draftKey(s),{...pending,revision:saved.revision});}catch(e){if(current(s)){$('memoryStatus').replaceChildren(document.createTextNode(err(e)),button('重试保存',()=>void save()));}}});saves=work;return work;}
 async function media(memory,host,full=false){const s=snap();for(const item of memory.media||[]){const type=item.type||item.mime?.split('/')[0];if(!['image','video','audio'].includes(type))continue;const element=node(type==='image'?'img':type,'memory-media');if(type==='image'){element.alt=item.name||memory.title||'回忆照片';element.loading='lazy';}else{element.controls=full;element.preload='metadata';element.muted=!full;}host.append(element);try{let url=urls.get(item.path);if(!url){const blob=await mediaBlob(s.room,item.path);if(!current(s))return;url=URL.createObjectURL(blob);urls.set(item.path,url);}if(current(s))element.src=url;}catch{element.replaceWith(node('small','',item.name||'附件暂时无法打开'));}}}
 function card(memory,index=0){const el=node('article','memory-card'+(memory.id.startsWith('message:')?' msg':'')+(memory.kind==='anniversary'?' wall-event':'')+(memory.media?.length?' has-photo':''));el.tabIndex=0;el.dataset.memoryId=memory.id;el.dataset.kind=memory.kind;el.style.setProperty('--paper-index',index%5);el.style.setProperty('--tilt',((index%5)-2)*.7+'deg');el.setAttribute('aria-label',(memory.title||memory.body).slice(0,80));if(selecting){const select=node('input');select.type='checkbox';select.checked=selected.has(memory.id);select.setAttribute('aria-label','选择回忆');select.onchange=()=>{select.checked?selected.add(memory.id):selected.delete(memory.id);selection();};el.append(select);}const front=node('div','memory-card-front');if(memory.media?.length)void media(memory,front);if(memory.title)front.append(node('h4','',memory.title));front.append(node('p','',memory.body.slice(0,220)),node('time','',memory.date));if(memory.tags?.length)front.append(node('small','memory-tags',memory.tags.slice(0,3).map(t=>'#'+t).join(' ')));front.append(node('i','paper-mark',index%3===0?'♡':'✧'));const back=node('div','memory-card-back');back.append(node('p','',memory.back||'暂无背面记录'),node('small','',(memory.tags||[]).map(t=>'#'+t).join(' ')));el.append(front,back);const actions=node('div','memory-card-actions');actions.append(button('翻面',e=>{el.classList.toggle('flipped');}),button('详情',()=>showDetail(memory)));el.append(actions);el.ondblclick=e=>{if(!e.target.closest('button,input'))showDetail(memory);};el.onkeydown=e=>{if(e.key==='Enter'&&e.target===el)showDetail(memory);};el.onclick=e=>{if(!e.target.closest('button,input')){focus(el);if(selecting){selected.has(memory.id)?selected.delete(memory.id):selected.add(memory.id);el.querySelector('input').checked=selected.has(memory.id);selection();}}};return el;}
 function focus(element){const stage=element.closest('.memory-stage');if(!stage)return;const r=stage.getBoundingClientRect(),b=element.getBoundingClientRect();stage.style.setProperty('--light-x',b.x+b.width/2-r.x+'px');stage.style.setProperty('--light-y',b.y+b.height/2-r.y+'px');}
 function filteredRows(){const tag=$('memoryTag').value.trim();return rows.filter(r=>(!$('memoryDate').value||r.date===$('memoryDate').value)&&(!tag||[r.title,r.body,...(r.tags||[])].some(t=>t?.includes(tag)))&&(kind==='all'||kind==='image'&&r.media?.some(m=>(m.type||m.mime?.split('/')[0])==='image')||kind==='text'&&['text','memory'].includes(r.kind)||r.kind===kind));}
 function optics(stage){
  stage.classList.toggle('dark',dark);stage.append(node('div','memory-shade'));
  const bar=node('div','memory-optics');bar.innerHTML='<div class="memory-light-control"><button id="memoryLight" aria-pressed="false">关灯</button><label id="memoryBeamControl" hidden>光圈直径<input id="memoryBeam" type="range" min="12" max="90" step="1" aria-label="光圈直径"/><output id="memoryBeamValue"></output></label></div><div class="memory-zoom-control"><button id="memoryZoomOut" aria-label="缩小回忆">−</button><button id="memoryZoomReset" aria-label="恢复默认缩放">100%</button><button id="memoryZoomIn" aria-label="放大回忆">＋</button></div>';
  box.append(bar);lightPercent=Number(storeGet(opticsKey(),34));if(!Number.isFinite(lightPercent))lightPercent=34;lightPercent=Math.max(12,Math.min(90,lightPercent));
  const update=()=>{stage.style.setProperty('--light-radius',Math.min(stage.clientWidth,stage.clientHeight)*lightPercent/200+'px');$('memoryLight').textContent=dark?'开灯':'关灯';$('memoryLight').setAttribute('aria-pressed',String(dark));$('memoryBeamControl').hidden=!dark;$('memoryBeam').value=String(lightPercent);$('memoryBeamValue').textContent=lightPercent+'%';};
  $('memoryLight').onclick=()=>{dark=!dark;stage.classList.toggle('dark',dark);update();};$('memoryBeam').oninput=()=>{lightPercent=Number($('memoryBeam').value);storeSet(opticsKey(),lightPercent);update();};
  $('memoryZoomIn').onclick=()=>viewport?.zoom(viewport.scale*1.2);$('memoryZoomOut').onclick=()=>viewport?.zoom(viewport.scale/1.2);$('memoryZoomReset').onclick=()=>viewport?.reset();update();
 }
 function render(){
  collection();if(pane.hidden||box.hidden||$('relationSpace').inert)return;
  const filtered=filteredRows(),currentMode=mode;
  const key=JSON.stringify([mode,filtered.slice(0,mode==='disc'?filtered.length:visibleLimit),selecting,[...selected],profile.data.positions,profile.data.links,box.clientWidth,box.clientHeight]);
  if(renderKey===key&&box.firstElementChild)return;
  renderKey=key;viewport?.destroy();viewport=null;cancelAnimationFrame(inertia);
  for(const b of chrome.querySelectorAll('[data-memory-mode]')){b.classList.toggle('active',b.dataset.memoryMode===mode);b.setAttribute('aria-pressed',String(b.dataset.memoryMode===mode));}
  for(const b of chrome.querySelectorAll('[data-memory-kind]'))b.setAttribute('aria-pressed',String(b.dataset.memoryKind===kind));
  pane.dataset.memoryView=mode;box.replaceChildren();box.dataset.mode=mode;
  if(state.spacePanel==='wallSpace')$('spaceTitle').textContent={notes:'回忆墙',board:'回忆录 · 线索板',disc:'回忆录 · 唱片机'}[mode];
  const stage=node('div','memory-stage '+(mode==='board'?'clue-stage':mode==='disc'?'disc-stage':'note-stage'));
  const surface=node('div','memory-surface');stage.append(surface);box.append(stage);optics(stage);lastWidth=box.clientWidth;lastHeight=box.clientHeight;
  const layout=memoryLayout(stage.clientWidth,stage.clientHeight);stage.style.setProperty('--card-width',layout.card+'px');stage.style.setProperty('--memory-gap',layout.gap+'px');stage.style.setProperty('--memory-padding',layout.padding+'px');stage.style.setProperty('--memory-columns',layout.columns);
  let single=null;
  if(!filtered.length){const empty=node('div','memory-empty');empty.innerHTML=poetryMarkup(7,true);empty.append(node('p','daily-empty','还没有符合条件的回忆。'),button('写张便签',()=>$('memoryAdd').click(),'btn ghost'));surface.append(empty);applyPoetry(empty);}
  else if(mode==='disc')single=disc(surface,filtered);
  else if(mode==='board')single=board(surface,filtered.slice(0,visibleLimit),layout);
  else{const grid=node('div','memory-note-grid');filtered.slice(0,visibleLimit).forEach((r,i)=>grid.append(card(r,i)));surface.append(grid);}
  if(mode!=='disc'&&filtered.length>visibleLimit)surface.append(button('再看看更早的回忆',()=>{visibleLimit+=36;render();},'memory-more btn ghost'));
  viewport=createMemoryViewport({stage,surface,initial:viewStates[mode]||single?.initialView,getBounds:single?.getBounds,onChange:value=>{viewStates[currentMode]=value;stage.style.setProperty('--canvas-height',stage.clientHeight+'px');stage.dataset.compact=String(stage.clientHeight<460);stage.style.setProperty('--light-radius',Math.min(stage.clientWidth,stage.clientHeight)*lightPercent/200+'px');if($('memoryZoomReset'))$('memoryZoomReset').textContent=Math.round(value.scale*100)+'%';},
   onHover:p=>{if(dark){stage.style.setProperty('--light-x',p.x+'px');stage.style.setProperty('--light-y',p.y+'px');}},
   onSingle:(e,p)=>{lastTap=lastTap&&e.timeStamp-lastTap.time<350?lastTap:null;if(dark)return {move(){lastTap=null;}};return single?.(e,p);},
   onTap:(target,e)=>{const el=target.closest('[data-memory-id]');if(!el)return;const id=el.dataset.memoryId,m=rows.find(r=>r.id===id);if(!m)return;focus(el);if(selecting){selected.has(id)?selected.delete(id):selected.add(id);el.querySelector('input').checked=selected.has(id);selection();}else if(mode==='disc'||lastTap?.id===id&&e.timeStamp-lastTap.time<350){showDetail(m);lastTap=null;}else lastTap={id,time:e.timeStamp};}
  });selection();
 }
 function board(surface,visible,layout){
  const canvas=node('div','clue-canvas');surface.append(canvas);
  const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.classList.add('clue-lines');canvas.append(svg);
  const positions=new Map(),elements=new Map(),rowHeights=[];
  for(const [i,m] of visible.entries()){
   const el=card(m,i);canvas.append(el);elements.set(m.id,el);
   const row=Math.floor(i/layout.columns);rowHeights[row]=Math.max(rowHeights[row]||0,el.offsetHeight+12);
  }
  const rowTops=[];let bottom=layout.padding;
  for(const h of rowHeights){rowTops.push(bottom);bottom+=h+layout.gap;}
  canvas.style.height=Math.max(surface.parentElement.clientHeight,bottom-layout.gap+layout.padding)+'px';
  const stage=surface.parentElement;
  // Keep the original normalisation so existing layouts remain in the same place.
  // Positions outside the unscaled canvas are valid when the board is zoomed out.
  const baseSize=el=>({x:Math.max(8,canvas.clientWidth-el.offsetWidth-8),y:Math.max(12,canvas.clientHeight-el.offsetHeight-8)});
  const clamp=(value,min,max)=>Math.min(max,Math.max(min,value));
  const shape=el=>{const w=el.offsetWidth,h=el.offsetHeight,m=new DOMMatrixReadOnly(getComputedStyle(el).transform);return {w,h,ox:(Math.abs(m.a)*w+Math.abs(m.c)*h-w)/2,oy:(Math.abs(m.b)*w+Math.abs(m.d)*h-h)/2};};
  let extended=false;
  for(const [i,m] of visible.entries()){
   const el=elements.get(m.id),saved=profile.data.positions?.[m.id],limit=baseSize(el);
   const nx=saved?.nx??saved?.x/910,ny=saved?.ny??saved?.y/Math.max(850,canvas.clientHeight);
   const pos={x:Number.isFinite(nx)?nx*limit.x:clamp(layout.padding+(i%layout.columns)*(layout.card+layout.gap),8,limit.x),y:Number.isFinite(ny)?ny*limit.y:clamp(rowTops[Math.floor(i/layout.columns)]+(i%2)*12,12,limit.y)};
   extended ||= pos.x<0||pos.y<0||pos.x>limit.x||pos.y>limit.y;
   positions.set(m.id,pos);el.style.left=pos.x+'px';el.style.top=pos.y+'px';
  }
  function draw(){svg.replaceChildren();for(const link of memoryLinks(visible,profile.data.links||[])){const a=positions.get(link.from),b=positions.get(link.to);if(!a||!b)continue;const line=document.createElementNS(svg.namespaceURI,'line');line.setAttribute('x1',a.x+elements.get(link.from).offsetWidth*.5);line.setAttribute('y1',a.y+3);line.setAttribute('x2',b.x+elements.get(link.to).offsetWidth*.5);line.setAttribute('y2',b.y+3);const title=document.createElementNS(svg.namespaceURI,'title');title.textContent=link.label;line.append(title);line.dataset.relation=link.label;svg.append(line);}}draw();
  const drag=(e,start)=>{const el=e.target.closest('[data-memory-id]');if(!el||selecting)return null;const id=el.dataset.memoryId,pos=positions.get(id),before={...pos},grab={x:start.x-pos.x,y:start.y-pos.y},s=shape(el);el.classList.add('is-dragging');const paint=()=>{el.style.left=pos.x+'px';el.style.top=pos.y+'px';draw();};
   return {move(p){
    lastTap=null;const b=viewport.visibleWorld,pad=8/viewport.scale;
    const left=b.left+pad+s.ox,right=b.right-pad-s.w-s.ox,top=b.top+pad+s.oy,bottom=b.bottom-pad-s.h-s.oy;
    // Inverse-transform the visible panel, not the smaller, transformed canvas.
    // Oversized cards can still move between their two edges at high zoom.
    pos.x=clamp(p.x-grab.x,Math.min(left,right),Math.max(left,right));pos.y=clamp(p.y-grab.y,Math.min(top,bottom),Math.max(top,bottom));paint();
   },end(moved){el.classList.remove('is-dragging');if(moved){const limit=baseSize(el);profile.data.positions={...profile.data.positions,[id]:{nx:pos.x/limit.x,ny:pos.y/limit.y}};void save();}},cancel(){lastTap=null;Object.assign(pos,before);el.classList.remove('is-dragging');paint();}};
  };
  const explored={left:0,top:0,right:canvas.clientWidth,bottom:surface.offsetHeight};
  drag.getBounds=scale=>{
   const w=canvas.clientWidth,h=surface.offsetHeight,extraX=Math.max(0,(stage.clientWidth/scale-w)/2),extraY=Math.max(0,(stage.clientHeight/scale-h)/2),pad=8/scale;
   // Moving a card inward must not shrink explored space and snap the camera on release.
   for(const [id,pos] of positions){const s=shape(elements.get(id));explored.left=Math.min(explored.left,pos.x-s.ox-pad);explored.top=Math.min(explored.top,pos.y-s.oy-pad);explored.right=Math.max(explored.right,pos.x+s.w+s.ox+pad);explored.bottom=Math.max(explored.bottom,pos.y+s.h+s.oy+pad);}
   return {left:Math.min(-extraX,explored.left),top:Math.min(-extraY,explored.top),right:Math.max(w+extraX,explored.right),bottom:Math.max(h+extraY,explored.bottom)};
  };
  // Reopening a saved, spread-out board must not hide cards beyond the base canvas.
  if(extended){const b=drag.getBounds(1),scale=clamp(Math.min(stage.clientWidth/(b.right-b.left),stage.clientHeight/(b.bottom-b.top)),.5,1);drag.initialView={scale,x:(stage.clientWidth-(b.left+b.right)*scale)/2,y:(stage.clientHeight-(b.top+b.bottom)*scale)/2};}
  return drag;
 }
 function discCard(memory,index){const el=node('article','record-memory'+(memory.media?.length?' has-photo':'')+(memory.id.startsWith('message:')?' msg':''));el.dataset.memoryId=memory.id;el.dataset.kind=memory.kind;if(selecting){const c=node('input');c.type='checkbox';c.checked=selected.has(memory.id);c.setAttribute('aria-label','选择回忆');c.onchange=()=>{c.checked?selected.add(memory.id):selected.delete(memory.id);selection();};el.append(c);}void media(memory,el);el.append(node('time','',memory.date),node('h4','',memory.title||({music:'同一段旋律',anniversary:'记得这一天',diary:'日记里的一页'})[memory.kind]||'时光片段'),node('p','',memory.body.slice(0,index?65:150)),button('展开 ›',()=>showDetail(memory)));el.ondblclick=()=>showDetail(memory);return el;}
 function disc(stage,items){
  cancelAnimationFrame(inertia);const record=node('div','memory-disc');record.tabIndex=0;record.setAttribute('role','slider');record.setAttribute('aria-label','转动唱片浏览回忆');record.setAttribute('aria-valuemin','1');record.setAttribute('aria-valuemax',String(items.length));record.append(node('span','memory-disc-label','MEMORIES'));stage.append(record);
  const memories=node('div','disc-memories');stage.append(memories);const caption=node('div','disc-caption');caption.innerHTML=poetryMarkup(5,true);stage.append(caption);applyPoetry(caption);let lastIndex=-1;
  const position=()=>{record.style.setProperty('--disc-angle',angle+'deg');const i=discIndex(angle,items.length);record.setAttribute('aria-valuenow',String(i+1));if(i!==lastIndex){lastIndex=i;memories.replaceChildren(...[0,1,2,3].slice(0,items.length).map(n=>discCard(items[(i+n)%items.length],n)));}};position();
  record.onkeydown=e=>{if(['ArrowDown','ArrowUp','ArrowRight','ArrowLeft'].includes(e.key)){e.preventDefault();angle+=['ArrowDown','ArrowRight'].includes(e.key)?30:-30;position();profile.data.angle=angle;void save();}};
  stage.append(node('small','disc-hint','滑动唱片切换回忆 · 双指缩放'));
  return (e,p)=>{if(!e.target.closest('.memory-disc'))return null;cancelAnimationFrame(inertia);const original=angle;let last=p,t=performance.now(),velocity=0;return {move(next){lastTap=null;const now=performance.now(),dx=next.x-last.x,dy=next.y-last.y,delta=(Math.abs(dx)>Math.abs(dy)?-dx:dy)*.55;angle+=delta;velocity=delta/Math.max(10,now-t)*16;last=next;t=now;position();},end(moved){if(!moved)return;const tick=()=>{angle+=velocity;velocity*=.94;position();if(Math.abs(velocity)>.12&&!matchMedia('(prefers-reduced-motion: reduce)').matches)inertia=requestAnimationFrame(tick);else{profile.data.angle=angle;void save();}};tick();},cancel(){lastTap=null;angle=original;position();}};};
 }
 function selection(){ $('memorySelection').hidden=!selecting;$('memorySelectedCount').textContent=`已选 ${selected.size} 条`;$('memoryFilmAdd').disabled=!selected.size||!filmOpen;$('memorySelect').textContent=selecting?'完成选择':'多选';}
 $('memorySelect').onclick=()=>{tools(false);selecting=!selecting;render();};$('memorySelectAll').onclick=()=>{filteredRows().forEach(r=>selected.add(r.id));render();};$('memoryFilmAdd').onclick=()=>filmOpen?.([...selected]);
 chrome.querySelectorAll('[data-memory-mode]').forEach(b=>b.onclick=()=>{tools(false);if(mode===b.dataset.memoryMode)return;mode=b.dataset.memoryMode;profile.data.view=mode;void save();render();});$('memorySummary').onchange=()=>{profile.data.summary=$('memorySummary').checked;void save();render();};for(const id of ['memoryDate','memoryTag'])$(id).oninput=render;$('memoryClear').onclick=()=>{$('memoryDate').value='';$('memoryTag').value='';render();};
 function showDetail(memory){cancelAnimationFrame(inertia);box.hidden=true;detail.hidden=false;detail.replaceChildren();const head=node('div','memory-detail-head');head.append(button('‹ 回到墙上',()=>{detail.hidden=true;box.hidden=false;render();}),button('补充记录',()=>annotate(memory)));detail.append(head,node('time','',memory.date),node('h3','',memory.title||'记得这一刻'));void media(memory,detail,true);detail.append(node('p','memory-full-text',memory.body));if(memory.private)detail.append(node('small','','仅自己可见'));const back=node('div','memory-back-copy');back.hidden=true;back.append(node('p','memory-full-text',memory.back||'这里还没有背面的文字。'),node('p','',(memory.tags||[]).map(t=>'#'+t).join(' ')));detail.append(button('翻到背面',()=>back.hidden=!back.hidden),back);if(filmOpen)detail.append(button('加入胶片',()=>filmOpen([memory.id])));const links=memoryLinks(rows,profile.data.links||[]).filter(l=>l.from===memory.id||l.to===memory.id);for(const l of links){const other=rows.find(r=>r.id===(l.from===memory.id?l.to:l.from));if(other)detail.append(button(`${l.label} · ${(other.title||other.body).slice(0,35)}`,()=>showDetail(other)));}const select=node('select');select.setAttribute('aria-label','关联另一条回忆');select.append(Object.assign(node('option','','关联另一条回忆'),{value:''}),...rows.filter(r=>r.id!==memory.id).map(r=>Object.assign(node('option','',`${r.date} ${(r.title||r.body).slice(0,22)}`),{value:r.id})));detail.append(select,button('连上线索',()=>{if(!select.value)return;profile.data.links=[...(profile.data.links||[]),{from:memory.id,to:select.value,label:'主动关联'}];void save();showDetail(memory);}));}
 function field(form,key,label,value='',type='text'){const l=node('label','field'),el=node(type==='textarea'?'textarea':'input');if(type!=='textarea')el.type=type;else el.rows=4;el.name=key;el.value=value||'';el.setAttribute('aria-label',label);el.maxLength=type==='textarea'?20000:120;l.append(node('span','',label),el);form.insertBefore(l,form.querySelector('[type=submit]'));return el;}
 function form(title,save){tools(false);editor.hidden=false;editor.replaceChildren();const f=node('form','daily-form');f.append(node('h4','',title));const b=node('button','btn primary','保存');b.type='submit';f.append(button('取消',()=>editor.hidden=true));editor.append(f);f.onsubmit=async e=>{e.preventDefault();b.disabled=true;const s=snap();try{await save(f,s);if(current(s)){editor.hidden=true;detail.hidden=true;box.hidden=false;render();}}catch(e){if(current(s))toast(err(e));}finally{b.disabled=false;}};f.append(b);return f;}
 function annotate(memory){const f=form('把线索记清楚',async f=>{const parts=key=>f.elements[key].value.split(/[,，、]/).map(t=>t.trim()).filter(Boolean);profile.data.annotations={...profile.data.annotations,[memory.id]:{back:f.elements.back.value,tags:parts('tags'),location:f.elements.location.value,people:parts('people'),event:f.elements.event.value}};await save();});for(const [key,label,type,value] of [['back','背面的文字','textarea',memory.back],['tags','标签（逗号分隔）','text',(memory.tags||[]).join('，')],['location','地点','text',memory.location],['people','人物（逗号分隔）','text',(memory.people||[]).join('，')],['event','同一事件的名字','text',memory.event]])field(f,key,label,value,type);}
 $('memoryAdd').onclick=()=>{if(!state.secure){toast('请在邀请房间里留下新便签。');return;}const id=randomId();const f=form('留下一个瞬间',async(f,s)=>{const files=[...f.elements.media.files];if(files.length>8)throw new Error('一张便签最多放 8 个附件。');const media=[];for(const file of files){media.push(await daily.upload(file,s,uploads));if(!current(s))return;}await daily.saveEntry({id,room_id:s.room,owner_user_id:s.userId,kind:'memory',visibility:f.elements.private.checked?'private':'shared',title:f.elements.title.value,body:f.elements.body.value,event_date:f.elements.date.value,data:{media,tags:f.elements.tags.value.split(/[,，、]/).map(t=>t.trim()).filter(Boolean)}});if(current(s))await refresh();});field(f,'title','标题');field(f,'body','想留下的话','','textarea');field(f,'date','日期',localDate(),'date').required=true;field(f,'tags','标签');const file=field(f,'media','图片、视频、音频','','file');file.multiple=true;file.accept='image/*,video/*,audio/*';const privateBox=field(f,'private','仅自己可见','','checkbox');privateBox.checked=false;};
 document.addEventListener('mailbox:space-open',()=>{if(state.spacePanel==='wallSpace'){render();if(Date.now()-lastRefreshAt>15000)void refresh();}});const suspend=()=>{cancelAnimationFrame(resizeFrame);cancelAnimationFrame(inertia);detail.querySelectorAll('audio,video').forEach(el=>el.pause());};document.addEventListener('mailbox:space-close',suspend);document.addEventListener('mailbox:space-page',()=>{if(pane.hidden)suspend();});
 $('memorySearchToggle').onclick=()=>{const show=$('memoryFilters').hidden;$('memoryFilters').hidden=!show;$('memorySearchToggle').setAttribute('aria-expanded',String(show));if(show)$('memoryTag').focus();};
 chrome.querySelectorAll('[data-memory-kind]').forEach(b=>b.onclick=()=>{kind=b.dataset.memoryKind;render();});
 function resize(){
  resizeFrame=0;if(pane.hidden)return;
  // Keep the existing cards while the sidebar slides. Rebuilding the whole
  // board for intermediate widths stalls the animation on touch devices.
  if(pane.closest('.scene-shell')?.getAnimations().some(a=>a.transitionProperty==='grid-template-columns'&&a.playState==='running')){resizeFrame=requestAnimationFrame(resize);return;}
  render();
 }
 const resizeObserver=new ResizeObserver(()=>{if(!pane.hidden&&(Math.abs(lastWidth-box.clientWidth)>2||Math.abs(lastHeight-box.clientHeight)>2)){cancelAnimationFrame(resizeFrame);resizeFrame=requestAnimationFrame(resize);}});resizeObserver.observe(box);
 document.addEventListener('mailbox:calendar-change',event=>{if(event.detail.room!==state.room)return;calendar=event.detail.events;render();});
 function ready(){if(state.secure){const s=snap();stop=daily.watch(s.room,()=>{if(current(s)&&!pane.hidden)void refresh();});}}
 function reset(){epoch++;renderKey='';lastRefreshAt=0;viewport?.destroy();viewport=null;viewStates={};kind='all';lastTap=null;visibleLimit=36;stop?.();stop=null;cancelAnimationFrame(inertia);for(const url of urls.values())URL.revokeObjectURL(url);urls.clear();history=[];entries=[];calendar=[];listens=[];profile={data:{},revision:0};rows=[];reading=null;saves=Promise.resolve();selected.clear();mode='notes';dark=false;selecting=false;angle=0;box.replaceChildren();detail.replaceChildren();detail.hidden=true;box.hidden=false;editor.hidden=true;$('memoryDate').value='';$('memoryTag').value='';}
 async function resolve(id){collection();const existing=rows.find(r=>r.id===id);if(existing)return existing;if(id.startsWith('summary:'))return todaySummary(rows,id.slice(8));if(id.startsWith('music:')&&state.secure){const day=id.slice(6),s=snap(),report=await daily.rpc('mailbox_listen_report',{p_room:s.room,p_start:day,p_end:day});if(!current(s))return null;return memoryCollection({listens:report.daily}).find(r=>r.id===id);}return null;}
 return {ready,reset,render,refresh,resolve,get rows(){return collection();},getMedia:media,onFilm(fn){filmOpen=fn;selection();},async select(ids){selected=new Set(ids);selecting=true;box.hidden=false;detail.hidden=true;ui.openFeature('wallSpace');await refresh();render();}};
}
