import {client} from './backend.js?v=2.5.0';
import {listRows} from './daily-backend.js?v=2.5.0';
const take=r=>{if(r.error)throw r.error;return r.data;};
export async function readLibrary(room){const sb=client(true),tables=['music_tracks','music_likes','music_colors'];const rows=await Promise.all(tables.map(async table=>{let all=[];for(let offset=0;offset<20000;offset+=500){const part=take(await sb.from(table).select('*').eq('room_id',room).order('owner_user_id').range(offset,offset+499))||[];all.push(...part);if(part.length<500)return all;}throw new Error('音乐记录较多，请稍后再试。');}));return {tracks:rows[0],likes:rows[1],colors:rows[2],playlists:await listRows('music_playlists',room)};}
export async function track(row){return take(await client(true).from('music_tracks').upsert(row,{onConflict:'room_id,owner_user_id,track_key'}).select().single());}
export async function like(row,enabled){const q=client(true).from('music_likes');return enabled?take(await q.upsert(row,{onConflict:'room_id,owner_user_id,track_key'}).select()):take(await q.delete().eq('room_id',row.room_id).eq('owner_user_id',row.owner_user_id).eq('track_key',row.track_key));}
export async function color(row){return take(await client(true).from('music_colors').upsert(row,{onConflict:'room_id,owner_user_id'}).select().single());}
export async function playlist(row){if(!row.revision){const r=await client(true).from('music_playlists').insert(row).select().single();if(r.error?.code==='23505'){const old=take(await client(true).from('music_playlists').select('*').eq('id',row.id).single());if(old.title===row.title&&JSON.stringify(old.track_keys)===JSON.stringify(row.track_keys))return old;}return take(r);}const {id,...fields}=row,r=take(await client(true).from('music_playlists').update({...fields,revision:row.revision+1}).eq('id',id).eq('revision',row.revision).select().maybeSingle());if(!r)throw new Error('歌单刚被另一端修改，请刷新后再试。');return r;}
export async function removePlaylist(id){return take(await client(true).from('music_playlists').delete().eq('id',id));}
export const rpc=async(name,args)=>take(await client(true).rpc(name,args));
export function watch(room,changed){const sb=client(true),channel=sb.channel('music-'+crypto.randomUUID());for(const table of ['music_tracks','music_likes','music_colors','music_playlists'])channel.on('postgres_changes',{event:'*',schema:'public',table,filter:'room_id=eq.'+room},changed);channel.subscribe();return()=>sb.removeChannel(channel);}
