import {uiIcon} from './ui-icons.js?v=2.7.5';
import {readTrackInfo,inspectLyrics,titleFromFilename} from './music-import-core.js?v=2.7.5';
import {bytesLabel} from './feature-core.js?v=2.7.5';

export function initMusicImport({$,node,state,toast,sheet,onSave,onCancel,onPreview,getLegacyNote=()=>''}){
 const page=node('section','music-import-page');page.id='musicImportPage';page.hidden=true;page.setAttribute('aria-label','导入歌曲与歌词');
 page.innerHTML=`<header class="import-heading"><button id="musicImportBack" class="import-back" type="button" aria-label="返回一起听">${uiIcon('back')}</button><div><h2>导入歌曲与歌词</h2><p>本机音频、歌词与封面，在这里一起整理。</p></div><ol class="import-steps"><li class="active"><b>1</b><span>选择音频</span></li><li><b>2</b><span>添加歌词</span></li><li><b>3</b><span>确认信息</span></li></ol></header>
 <div class="music-import-layout"><div class="import-main">
 <section class="import-card"><header class="import-section-title"><span>1</span><div><h3>选择本机歌曲</h3><small>支持 MP3 / WAV / FLAC / M4A / OGG，单首不超过 80 MB</small></div></header>
 <div class="audio-drop import-drop" id="musicAudioDrop"><div>${uiIcon('upload')}<b>拖拽音频文件到这里</b><small>或从设备中选择，可以一次选多首</small><button id="musicChooseAudio" class="btn ghost" type="button">${uiIcon('folder')}选择文件</button></div><span class="import-record" aria-hidden="true"></span></div><input id="listenFile" type="file" multiple accept="audio/*,.mp3,.wav,.flac,.m4a,.ogg" hidden/>
 <div class="import-selection-heading"><h4>已选择的歌曲 <span id="musicImportCount">0</span></h4><button id="musicImportClear" class="text-btn" type="button">清空</button></div><div id="musicImportQueue" class="import-queue"></div><div class="import-file-facts" id="musicImportFacts"></div><svg id="musicImportWave" class="import-wave" viewBox="0 0 600 46" preserveAspectRatio="none" aria-label="音频波形" hidden></svg></section>
 <section class="import-card"><header class="import-section-title"><span>2</span><div><h3>导入歌词</h3><small>支持 LRC 时间轴与 TXT 原文，也可以直接粘贴。</small></div></header><div class="import-lyric-tabs" role="tablist" aria-label="歌词导入方式"><button id="musicLyricsUploadTab" role="tab" aria-selected="true" type="button">${uiIcon('file')}上传歌词文件</button><button id="musicLyricsPasteTab" role="tab" aria-selected="false" type="button">${uiIcon('edit')}直接粘贴歌词</button></div>
 <div id="musicLyricsDrop" class="lyrics-drop import-drop">${uiIcon('file')}<div><b>拖拽歌词文件到这里</b><small id="musicLyricsFilename">为当前选中的歌曲添加歌词</small></div><button id="musicChooseLyrics" class="btn ghost" type="button">${uiIcon('folder')}选择歌词文件</button></div><input id="lyricsFile" type="file" accept=".lrc,.txt,text/plain" hidden/><textarea id="musicImportLyrics" rows="6" maxlength="20000" aria-label="粘贴歌词" placeholder="[00:00.00] 第一行歌词&#10;也可以粘贴没有时间轴的纯文字歌词" hidden></textarea><p id="musicLyricsStatus" class="import-feedback" role="status"></p><details id="musicLegacyNotes" hidden><summary>旧版歌词与备注</summary><textarea id="musicLegacyText" aria-label="旧版本机歌词与备注" readonly rows="4"></textarea></details></section>
 <section class="import-card import-assist"><span class="import-assist-symbol" aria-hidden="true">${uiIcon('spark')}</span><div><h3>导入助手</h3><p>读取文件中的歌曲资料和封面，帮你检查歌词时间轴。</p><div><button id="musicExtractCover" class="btn ghost" type="button">提取内嵌封面</button><button id="musicCheckLyrics" class="btn ghost" type="button">检查歌词时间轴</button><button id="musicFillInfo" class="btn ghost" type="button">补全歌曲信息</button></div></div></section></div>
 <aside class="import-side"><section class="import-card import-preview"><h3>歌曲预览</h3><div id="musicImportArtwork" class="import-artwork"><button id="musicPreviewArtworkPlay" type="button" aria-label="试听歌曲">${uiIcon('play')}</button></div><div class="import-preview-heading"><div><h3 id="musicPreviewTitle">等待一首歌</h3><small id="musicPreviewArtist">选择文件后，即可试听</small></div><button id="musicImportFavorite" class="import-icon" type="button" aria-label="导入后加入私人收藏" aria-pressed="false">${uiIcon('heart')}</button></div><input id="musicPreviewSeek" aria-label="导入预览进度" type="range" min="0" max="1" step=".1" value="0" disabled/><div class="import-times"><span id="musicPreviewTime">00:00</span><span id="musicPreviewDuration">00:00</span></div><div class="import-transport"><button id="musicPreviewShuffle" class="import-icon" type="button" aria-label="随机试听" aria-pressed="false">${uiIcon('shuffle')}</button><button id="musicPreviewPrevious" class="import-icon" type="button" aria-label="试听上一首">${uiIcon('prev')}</button><button id="musicPreviewPlay" class="import-play" type="button" aria-label="试听歌曲">${uiIcon('play')}</button><button id="musicPreviewNext" class="import-icon" type="button" aria-label="试听下一首">${uiIcon('next')}</button><button id="musicPreviewQueue" class="import-icon" type="button" aria-label="查看已选歌曲">${uiIcon('list')}</button></div></section>
 <section class="import-card import-metadata"><header><h3>歌曲信息 <small>可编辑</small></h3><button id="musicSmartFill" class="btn ghost" type="button">${uiIcon('edit')}智能填充</button></header><div class="import-metadata-grid"><div><label class="import-meta-field">${uiIcon('music')}<input id="musicImportTitle" aria-label="歌曲名称" maxlength="120" placeholder="歌曲名称"/></label><label class="import-meta-field"><span aria-hidden="true">♙</span><input id="musicImportArtist" aria-label="艺术家" maxlength="60" placeholder="未知艺术家"/></label><label class="import-meta-field">${uiIcon('folder')}<input id="musicImportAlbum" aria-label="专辑" maxlength="120" placeholder="未知专辑"/></label><label class="import-meta-field">${uiIcon('music')}<select id="musicImportGenre" aria-label="歌曲风格"><option value="">选择风格</option><option>流行</option><option>民谣</option><option>古典</option><option>轻音乐</option><option>摇滚</option><option>电子</option><option>爵士</option><option>其他</option></select></label></div><button id="musicChooseCover" class="import-cover" type="button"><span id="musicImportCover"></span><small>更换封面</small></button></div><input id="musicCoverFile" type="file" accept="image/jpeg,image/png,image/webp" hidden/></section>
 <section class="import-card import-save-card"><header class="import-section-title"><span>3</span><div><h3>给这首歌留一句话</h3><small>记下关于这首歌的心情，仅保存在本机。</small></div></header><textarea id="listenNotes" aria-label="歌曲备注" rows="3" maxlength="200" placeholder="这首歌，让你想起什么？"></textarea><small id="musicImportNoteCount">0 / 200</small><p id="musicImportStatus" class="import-feedback" role="status" aria-live="polite">音频和封面留在本机，保存后才加入音乐架。</p><div class="import-save-actions"><button id="musicImportCancel" class="btn ghost" type="button">取消</button><button id="musicImportSave" class="btn primary" type="button" disabled>保存并导入 ›</button></div></section></aside></div><audio id="musicPreviewAudio" preload="metadata"></audio>`;
 sheet.append(page);
 const audio=$('musicPreviewAudio');let drafts=[],selected=0,revision=0,previewURL='',busy=false,reading=false,shuffle=false,context=null;
 const current=()=>drafts[selected];const stamp=()=>({room:state.room,epoch:state.epoch,revision});const fresh=s=>s.room===state.room&&s.epoch===state.epoch&&s.revision===revision;
 const clock=n=>`${String(Math.floor((n||0)/60)).padStart(2,'0')}:${String(Math.floor((n||0)%60)).padStart(2,'0')}`;
 const status=text=>$('musicImportStatus').textContent=text;
 function keep(){const track=current();if(!track)return;for(const [key,id] of Object.entries({name:'musicImportTitle',artist:'musicImportArtist',album:'musicImportAlbum',genre:'musicImportGenre',note:'listenNotes',lyricsText:'musicImportLyrics'}))track[key]=$(id).value;}
 function artwork(el,cover){el.style.backgroundImage=cover?`url("${cover}")`:'';}
 function paint(){const track=current();$('musicImportCount').textContent=drafts.length;$('musicImportSave').disabled=busy||reading||!drafts.length;$('musicImportClear').disabled=busy||reading||!drafts.length;
  for(const id of ['musicImportTitle','musicImportArtist','musicImportAlbum','musicImportGenre','listenNotes','musicImportLyrics','musicChooseLyrics','musicChooseCover','musicImportFavorite','musicSmartFill','musicFillInfo','musicExtractCover','musicCheckLyrics'])$(id).disabled=busy||!track;
  $('musicImportQueue').replaceChildren(...drafts.map((t,i)=>{const row=node('div','import-track'+(i===selected?' selected':'')),choose=node('button','import-track-select'),art=node('span','import-track-art'),copy=node('span');choose.type='button';choose.disabled=busy;choose.setAttribute('aria-label','预览 '+t.name);artwork(art,t.coverData);copy.append(node('b','',t.name||t.file.name),node('small','',t.artist||'未知艺术家'));choose.append(art,copy);choose.onclick=()=>select(i);const remove=node('button','import-track-remove','×');remove.type='button';remove.setAttribute('aria-label','移除 '+t.name);remove.disabled=busy;remove.onclick=()=>{keep();drafts.splice(i,1);select(Math.min(selected,drafts.length-1),false);};row.append(choose,remove);return row;}));
  $('musicPreviewTitle').textContent=track?.name||'等待一首歌';$('musicPreviewArtist').textContent=track?[track.artist||'未知艺术家',track.album||'未知专辑'].join(' · '):'选择文件后，即可试听';
  for(const id of ['musicImportArtwork','musicImportCover'])artwork($(id),track?.coverData);$('musicImportFavorite').setAttribute('aria-pressed',String(!!track?.favorite));$('musicImportNoteCount').textContent=($('listenNotes').value.length||0)+' / 200';
  const info=track?.file;$('musicImportFacts').textContent=info?[info.name.split('.').at(-1).toUpperCase(),bytesLabel(info.size),track.duration?clock(track.duration):'时长读取中'].join(' · '):'还没有选择音频。';lyricsStatus();time();
  [...page.querySelectorAll('.import-steps li')].forEach((el,i)=>el.classList.toggle('active',i===0||i===1&&!!track||i===2&&!!track?.lyricsText));
 }
 function lyricsStatus(){const track=current(),report=inspectLyrics($('musicImportLyrics').value,track?.duration||0);$('musicLyricsStatus').textContent=report.message+(report.warnings.length?'。'+report.warnings.join('；'):'');return report;}
 function select(index,save=true){if(save)keep();selected=Math.max(0,index);audio.pause();if(previewURL)URL.revokeObjectURL(previewURL);previewURL='';const track=current();for(const [key,id] of Object.entries({name:'musicImportTitle',artist:'musicImportArtist',album:'musicImportAlbum',genre:'musicImportGenre',note:'listenNotes',lyricsText:'musicImportLyrics'}))$(id).value=track?.[key]||'';
  if(track?.genre&&!$('musicImportGenre').value){const opt=node('option','',track.genre);opt.value=track.genre;$('musicImportGenre').append(opt);$('musicImportGenre').value=track.genre;}
  $('musicLyricsFilename').textContent=track?.lyricsFilename||'为当前选中的歌曲添加歌词';if(track){previewURL=URL.createObjectURL(track.file);audio.src=previewURL;}else audio.removeAttribute('src');audio.load();paint();void wave(track);
 }
 async function coverData(blob){if(!blob||!['image/png','image/jpeg','image/webp'].includes(blob.type)||blob.size>8*1024*1024)throw new Error('请选择 8 MB 以内的 JPG、PNG 或 WebP 封面。');const bitmap=await createImageBitmap(blob);try{const scale=Math.min(1,640/Math.max(bitmap.width,bitmap.height)),canvas=document.createElement('canvas');canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);return canvas.toDataURL('image/jpeg',.84);}finally{bitmap.close();}}
 async function add(files){if(busy||reading)return;const s=stamp();keep();reading=true;paint();$('musicChooseAudio').disabled=true;try{if(drafts.length+files.length>20)throw new Error('每次最多整理 20 首歌曲。');status('正在读取歌曲资料…');for(const file of files){if(!file.size||file.size>80*1024*1024||!file.type.startsWith('audio/')&&!/\.(mp3|wav|flac|m4a|ogg)$/i.test(file.name))throw new Error('请选择不超过 80 MB 的音频文件。');if(drafts.some(t=>t.file.name===file.name&&t.file.size===file.size&&t.file.lastModified===file.lastModified))continue;const info=await readTrackInfo(file);if(!fresh(s))return;let cover='';if(info.cover)cover=await coverData(info.cover).catch(()=>'');if(!fresh(s))return;drafts.push({...info,file,cover:undefined,coverData:cover,embeddedCover:cover,lyricsText:'',note:'',favorite:false});}select(0,false);status('可以试听、调整歌曲资料，再保存到音乐架。');}catch(e){if(fresh(s))status(e.message);}finally{if(fresh(s)){reading=false;$('musicChooseAudio').disabled=false;paint();}}}
 async function lyrics(file){const track=current(),s=stamp();if(!track){status('先选择歌曲，再添加歌词。');return;}if(!file)return;try{if(file.size>200000)throw new Error('歌词文件请小于 200 KB。');const text=await file.text();if(!fresh(s)||current()!==track)return;$('musicImportLyrics').value=text.slice(0,20000);track.lyricsText=$('musicImportLyrics').value;track.lyricsFilename=file.name;$('musicLyricsFilename').textContent=file.name;lyricsStatus();}catch(e){status(e.message);}}
 function drop(id,handle){const el=$(id);el.ondragover=e=>{e.preventDefault();el.classList.add('drag-over');};el.ondragleave=()=>el.classList.remove('drag-over');el.ondrop=e=>{e.preventDefault();el.classList.remove('drag-over');if(!busy)void handle([...e.dataTransfer.files]);};}
 drop('musicAudioDrop',add);drop('musicLyricsDrop',files=>lyrics(files[0]));$('musicChooseAudio').onclick=()=>$('listenFile').click();$('listenFile').onchange=()=>void add([...$('listenFile').files]);$('musicChooseLyrics').onclick=()=>$('lyricsFile').click();$('lyricsFile').onchange=()=>void lyrics($('lyricsFile').files[0]);
 function lyricTab(paste){$('musicLyricsDrop').hidden=paste;$('musicImportLyrics').hidden=!paste;$('musicLyricsUploadTab').setAttribute('aria-selected',String(!paste));$('musicLyricsPasteTab').setAttribute('aria-selected',String(paste));if(paste)$('musicImportLyrics').focus();}
 $('musicLyricsUploadTab').onclick=()=>lyricTab(false);$('musicLyricsPasteTab').onclick=()=>lyricTab(true);$('musicImportLyrics').oninput=()=>{keep();lyricsStatus();};
 for(const id of ['musicImportTitle','musicImportArtist','musicImportAlbum','musicImportGenre','listenNotes'])$(id).addEventListener('input',()=>{keep();$('musicPreviewTitle').textContent=current()?.name||'未命名歌曲';$('musicPreviewArtist').textContent=[current()?.artist||'未知艺术家',current()?.album||'未知专辑'].join(' · ');$('musicImportNoteCount').textContent=$('listenNotes').value.length+' / 200';});
 $('musicChooseCover').onclick=()=>$('musicCoverFile').click();$('musicCoverFile').onchange=async()=>{const file=$('musicCoverFile').files[0],track=current(),s=stamp();if(!file||!track)return;try{const cover=await coverData(file);if(!fresh(s)||current()!==track)return;track.coverData=cover;paint();}catch(e){status(e.message);}};
 $('musicImportFavorite').onclick=()=>{if(current()){current().favorite=!current().favorite;paint();}};
 $('musicExtractCover').onclick=()=>{if(current()?.embeddedCover){current().coverData=current().embeddedCover;paint();status('已使用音频文件内的封面。');}else status('这份文件没有可读取的内嵌封面。点击更换封面，选择自己的图片。');};
 $('musicCheckLyrics').onclick=()=>{const report=lyricsStatus();status(report.message+(report.warnings.length?'。'+report.warnings.join('；'):'。'));};
 async function fillInfo(){const track=current(),s=stamp();if(!track)return;try{keep();const info=await readTrackInfo(track.file);if(!fresh(s)||current()!==track)return;for(const key of ['name','artist','album','genre'])if(info[key]&&(!track[key]||key==='name'&&track.name===titleFromFilename(track.file.name).name))track[key]=info[key];select(selected,false);status('已读取文件标签与文件名；未找到的资料可以手动填写。');}catch(e){status(e.message);}}
 $('musicSmartFill').onclick=$('musicFillInfo').onclick=()=>void fillInfo();
 function time(){const duration=Number.isFinite(audio.duration)?audio.duration:0;$('musicPreviewSeek').max=duration||1;$('musicPreviewSeek').value=audio.currentTime||0;$('musicPreviewSeek').disabled=!duration;$('musicPreviewTime').textContent=clock(audio.currentTime);$('musicPreviewDuration').textContent=clock(duration);for(const id of ['musicPreviewPlay','musicPreviewArtworkPlay']){$(id).disabled=!current();$(id).innerHTML=uiIcon(audio.paused?'play':'pause');$(id).setAttribute('aria-label',audio.paused?'试听歌曲':'暂停试听');}}
 async function toggle(){if(!current())return;try{if(audio.paused){onPreview();await audio.play();}else audio.pause();time();}catch{status('浏览器暂时无法播放这个音频，请尝试 MP3、M4A 或 WAV。');}}
 $('musicPreviewPlay').onclick=$('musicPreviewArtworkPlay').onclick=()=>void toggle();$('musicPreviewSeek').oninput=()=>{audio.currentTime=Number($('musicPreviewSeek').value);time();};audio.ontimeupdate=audio.onplay=audio.onpause=time;audio.onloadedmetadata=()=>{if(current())current().duration=Number.isFinite(audio.duration)?audio.duration:0;paint();};audio.onerror=()=>{if(current())status('这份音频无法预览，可以更换受支持的格式。');};
 function skip(step){if(!drafts.length)return;select(shuffle?Math.floor(Math.random()*drafts.length):(selected+step+drafts.length)%drafts.length);}
 $('musicPreviewPrevious').onclick=()=>skip(-1);$('musicPreviewNext').onclick=()=>skip(1);$('musicPreviewShuffle').onclick=()=>{shuffle=!shuffle;$('musicPreviewShuffle').setAttribute('aria-pressed',String(shuffle));};$('musicPreviewQueue').onclick=()=>$('musicImportQueue').scrollIntoView({block:'center',behavior:'smooth'});
 async function wave(track){const el=$('musicImportWave');el.toggleAttribute('hidden',true);el.replaceChildren();if(!track||track.file.size>20*1024*1024||!window.AudioContext)return;try{context||=new AudioContext();const buffer=await context.decodeAudioData(await track.file.arrayBuffer());if(track!==current()||page.hidden)return;const data=buffer.getChannelData(0),bars=[];for(let x=0;x<150;x++){let peak=0;const start=Math.floor(x*data.length/150),end=Math.floor((x+1)*data.length/150),step=Math.max(1,Math.floor((end-start)/60));for(let n=start;n<end;n+=step)peak=Math.max(peak,Math.abs(data[n]));bars.push(peak);}const max=Math.max(.001,...bars);el.innerHTML='<path d="'+bars.map((n,i)=>`M${i*4+2},${23-Math.max(1,n/max*20)}v${Math.max(2,n/max*40)}`).join(' ')+'" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"/>';el.toggleAttribute('hidden',false);}catch{/* Unsupported preview decoding does not block importing the original file. */}}
 $('musicImportSave').onclick=async()=>{if(busy||reading||!drafts.length)return;if(!state.ready){status('房间仍在连接中，请稍后保存。');return;}keep();if(drafts.some(t=>!t.name.trim())){status('请为每一首歌曲填写名称。');return;}const s=stamp();busy=true;paint();$('musicChooseAudio').disabled=true;status('正在保存歌曲与歌词…');try{const tracks=drafts.map(t=>{const report=inspectLyrics(t.lyricsText,t.duration);return {...t,name:t.name.trim(),lyrics:report.lyrics,plainLyrics:report.plainLyrics};});await onSave(tracks);if(!fresh(s))return;reset();onCancel();toast('已加入音乐架，歌曲与封面保存在本机。');}catch(e){if(fresh(s))status(e.message||'保存未完成，已选文件仍保留。');}finally{busy=false;$('musicChooseAudio').disabled=false;if(fresh(s))paint();}};
 function reset(){revision++;audio.pause();if(previewURL)URL.revokeObjectURL(previewURL);previewURL='';audio.removeAttribute('src');audio.load();drafts=[];selected=0;busy=false;reading=false;$('musicChooseAudio').disabled=false;for(const id of ['listenFile','lyricsFile','musicCoverFile'])$(id).value='';context?.close().catch(()=>{});context=null;select(0,false);}
 function cancel(){if(busy)return;reset();onCancel();}
 $('musicImportBack').onclick=$('musicImportCancel').onclick=cancel;$('musicImportClear').onclick=reset;
 document.addEventListener('mailbox:space-close',()=>audio.pause());document.addEventListener('mailbox:space-page',()=>audio.pause());document.addEventListener('mailbox:room-open',reset);
 return {open(track){const legacy=getLegacyNote();$('musicLegacyNotes').hidden=!legacy;$('musicLegacyText').value=legacy;if(!drafts.length&&track){drafts=[{...track,lyricsText:track.lyricsText||track.plainLyrics||track.lyrics?.map(line=>`[${clock(line.time)}]${line.text}`).join('\n')||''}];select(0,false);}else paint();},pause(){audio.pause();},reset};
}
