const $=(id)=>document.getElementById(id);const THEMES=["clean","ins-dark","warm-light","warm-dark"];const LABEL={clean:"Ins · 日间","ins-dark":"Ins · 夜间","warm-light":"暖色 · 日间","warm-dark":"暖色 · 夜间"};
function saveTheme(t){document.documentElement.dataset.theme=t;try{localStorage.setItem("theme.v2",t)}catch{}document.querySelector('meta[name="theme-color"]')?.setAttribute("content",t.includes("dark")?"#171819":t.startsWith("warm")?"#f5eee7":"#f6f6f4")}
function cycleTheme(){const now=document.documentElement.dataset.theme;saveTheme(THEMES[(THEMES.indexOf(now)+1)%THEMES.length]);toast2(LABEL[document.documentElement.dataset.theme])}
function initTheme(){let t="clean";try{t=localStorage.getItem("theme.v2")||"clean"}catch{}if(!THEMES.includes(t))t="clean";saveTheme(t);document.querySelectorAll("[data-theme-pick]").forEach(b=>b.addEventListener("click",()=>{saveTheme(b.dataset.themePick);toast2(`已切换：${LABEL[b.dataset.themePick]}`)}));["themeBtn","themeMenuBtn"].forEach(id=>$(id)?.addEventListener("click",e=>{e.preventDefault();e.stopImmediatePropagation();cycleTheme()},true))}
function toast2(text){const el=$("toast");if(!el)return;el.textContent=text;el.classList.add("show");setTimeout(()=>el.classList.remove("show"),2800)}
function drawer(open){$("relationSpace")?.classList.toggle("open",open);$("relationSpace")?.setAttribute("aria-hidden",String(!open))}
function daysSince(){let first=null;try{const key="relation.first."+(new URL(location.href).searchParams.get("room")||"home");first=localStorage.getItem(key);if(!first){first=new Date().toISOString();localStorage.setItem(key,first)}}catch{first=new Date().toISOString()}return Math.max(1,Math.floor((Date.now()-new Date(first).getTime())/86400000)+1)}
function initDrawer(){$("relationHandle")?.addEventListener("click",()=>drawer(true));$("relationClose")?.addEventListener("click",()=>drawer(false));$("relationDays").textContent=daysSince();document.querySelectorAll("[data-open-view]").forEach(b=>b.addEventListener("click",()=>{document.querySelector(`[data-view="${b.dataset.openView}"]`)?.click();drawer(false)}));let x=0;const room=$("room");room?.addEventListener("touchstart",e=>x=e.touches[0].clientX,{passive:true});room?.addEventListener("touchend",e=>{if(e.changedTouches[0].clientX-x<-70&&x>innerWidth*.65)drawer(true)},{passive:true})}
async function enableNotifications(){if(!("Notification" in window)){toast2("当前浏览器不支持系统通知");return}const p=await Notification.requestPermission();toast2(p==="granted"?"新留言系统通知已开启":"没有获得通知权限");try{if("serviceWorker" in navigator)await navigator.serviceWorker.register("./sw.js?v=1")}catch{}}
function notifyNew(){toast2("收到一条新留言");if(document.hidden&&Notification.permission==="granted"){try{new Notification("小小留言室",{body:"你有一条新留言",tag:"message-room"})}catch{}}}
function initMessageWatch(){const box=$("messages");if(!box)return;let ready=false,last="";const scan=()=>{const row=[...box.querySelectorAll(".msg")].at(-1);if(!row)return;const id=row.dataset.messageId||row.textContent;if(ready&&id!==last&&!row.classList.contains("mine"))notifyNew();last=id;ready=true};new MutationObserver(scan).observe(box,{childList:true,subtree:true});scan()}
function init(){initTheme();initDrawer();$("notifyBtn")?.addEventListener("click",enableNotifications);initMessageWatch();if("serviceWorker" in navigator)navigator.serviceWorker.register("./sw.js?v=1").catch(()=>{})}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init);else init();