import assert from 'node:assert/strict';
export async function runDaily({setup,check,secureId,user,friend,fixture,root}){
 const s=await setup({secure:true,rows:[fixture(1,secureId,'保留的旧聊天',friend,{author_id:friend})]}),p=s.page;
 await p.waitForFunction(()=>document.querySelector('#roomStatus').textContent.includes('左滑'));
 const open=async id=>{if(await p.locator('#relationSpace').evaluate(el=>el.inert))await p.locator('#relationHandle').click();if(!await p.locator('#spaceBack').evaluate(el=>el.hidden))await p.locator('#spaceBack').click();await p.locator(id==='diarySpace'?'[data-open-view=diary]':'#'+id+'Btn').click();};
 const editor=id=>p.locator('#'+id+' .daily-editor');const form=id=>editor(id).locator('form');
 const saved=async id=>editor(id).waitFor({state:'hidden'});
 await check('diary saves date, mood, labels and private photo then filters without replacing chat',async()=>{
  await open('diarySpace');await p.locator('#writeFromView').click();const f=form('diarySpace');await f.locator('[name=title]').fill('雨停之前');await f.locator('[name=body]').fill('今天很适合慢慢走。');await f.locator('[name=date]').fill('2026-09-29');await f.locator('[name=category]').selectOption('mood');await f.locator('[name=mood]').fill('平静');await f.locator('[name=tags]').fill('雨天，学校');await f.locator('[name=visibility]').selectOption('private');await f.locator('[name=media]').setInputFiles({name:'photo.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+/a9sAAAAASUVORK5CYII=','base64')});await f.locator('[type=submit]').click();await saved('diarySpace');assert.equal(s.control.daily.space_entries[0].visibility,'private');assert.equal(s.control.daily.space_entries[0].data.media.length,1);await p.locator('[data-diary-filter=mood]').click();assert.match(await p.locator('#diaryJournal').textContent(),/雨停之前/);assert.equal(await p.locator('#diaryEntries').isVisible(),false);assert.equal(await p.locator('#messages .msg').count(),1);
 });
 await check('goals record per-user completion and preserve check-in history',async()=>{
  await open('checkinSpace');await p.locator('#checkinSpace .daily-toolbar button').click();let f=form('checkinSpace');await f.locator('[name=title]').fill('一起散步');await f.locator('[type=submit]').click();await saved('checkinSpace');await p.getByRole('button',{name:'记录今天',exact:true}).click();f=form('checkinSpace');await f.locator('[name=body]').fill('走了二十分钟');await f.locator('[type=submit]').click();await saved('checkinSpace');assert.match(await p.locator('#checkinSpace .daily-list').textContent(),/今日已完成/);assert.match(await p.locator('#checkinSpace .daily-list').textContent(),/今日待打卡/);await p.locator('#checkinSpace summary').click();assert.match(await p.locator('#checkinSpace details').textContent(),/走了二十分钟/);
 });
 await check('ledger records exact cents, payer and private monthly total; todo persists completion',async()=>{
  await open('ledgerSpace');await p.locator('#ledgerSpace .daily-toolbar button').click();let f=form('ledgerSpace');await f.locator('[name=amount]').fill('12.34');await f.locator('[name=category]').fill('早餐');await f.locator('[name=paid]').selectOption(friend);await f.locator('[name=visibility]').selectOption('private');await f.locator('[type=submit]').click();await saved('ledgerSpace');assert.equal(s.control.daily.space_entries.find(r=>r.kind==='ledger').data.cents,1234);assert.match(await p.locator('.ledger-total').textContent(),/12.34/);
  await open('todoSpace');await p.locator('#todoSpace .daily-toolbar button').click();f=form('todoSpace');await f.locator('[name=title]').fill('看两页 C 语言');await f.locator('[type=submit]').click();await saved('todoSpace');await p.getByRole('checkbox',{name:'完成 看两页 C 语言'}).check();await p.locator('#todoSpace .is-done').waitFor();assert.equal(s.control.daily.space_entries.find(r=>r.kind==='todo').data.done,true);
 });
 await check('pocket requires QR, records confirmed deposits and supports leave and server-confirmed cooling cancellation',async()=>{
  await open('pocketSpace');await p.getByRole('button',{name:'创建第一个荷包'}).click();let f=form('pocketSpace');await f.locator('[name=title]').fill('我们的旅行');await f.locator('[name=target]').fill('100');await f.getByRole('button',{name:'下一步 →',exact:true}).click();await f.locator('[name=daily]').fill('10');await f.locator('[name=qr]').setInputFiles({name:'qr.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+/a9sAAAAASUVORK5CYII=','base64')});await f.locator('[type=submit]').click();await saved('pocketSpace');assert.equal(s.control.daily.pockets[0].target_cents,10000);
  await p.getByRole('button',{name:'＋ 存一笔',exact:true}).click();f=form('pocketSpace');await f.locator('[name=amount]').fill('50');await f.locator('[name=confirmed]').check();await f.locator('[type=submit]').click();await saved('pocketSpace');assert.match(await p.locator('.pocket-amount').textContent(),/50.00/);
  await p.getByRole('button',{name:'取出',exact:true}).click();f=form('pocketSpace');await f.locator('[name=amount]').fill('10');await f.locator('[name=reason]').fill('想买一本书');await f.locator('[data-cooling="48"]').click();await f.locator('[type=submit]').click();await saved('pocketSpace');assert.match(await p.locator('.pocket-pending').textContent(),/想买一本书/);assert.match(await p.locator('.pocket-amount').textContent(),/50.00/);assert.equal(await p.getByRole('button',{name:'到期再次确认'}).isDisabled(),true);await p.getByRole('button',{name:'到期再次确认'}).evaluate(el=>{el.disabled=false;el.click();});await p.locator('#noticeConfirm').click();await p.waitForFunction(()=>document.querySelector('#toast').textContent.includes('冷静期'));assert.equal(s.control.daily.pocket_entries[1].status,'pending');await p.getByRole('button',{name:'取消，继续存着'}).click();await p.locator('.pocket-pending').waitFor({state:'hidden'});
  await p.getByRole('button',{name:'写假条'}).click();f=form('pocketSpace');await f.locator('[name=reason]').fill('这两天休息');await f.locator('[type=submit]').click();await saved('pocketSpace');assert.match(await p.locator('#pocketSpace .daily-list').textContent(),/这两天休息/);
 });
 await check('wheel uses chosen amount in deposit form and reaching the goal renders a real settlement',async()=>{
  await p.getByRole('button',{name:'转盘存钱'}).click();let f=form('pocketSpace');await f.locator('[name=min]').fill('50');await f.locator('[name=max]').fill('50');await f.locator('[type=submit]').click();await p.getByRole('button',{name:'用这个金额存入'}).click();f=form('pocketSpace');assert.equal(await f.locator('[name=amount]').inputValue(),'50.00');await f.locator('[name=confirmed]').check();await f.locator('[type=submit]').click();await saved('pocketSpace');await p.locator('.pocket-complete').waitFor();assert.match(await p.locator('.pocket-complete').textContent(),/我们做到了/);await p.screenshot({path:root+'/test-results/daily-pocket-phone.png'});
 });
 await check('an interrupted deposit survives reload and retries the original ID without duplicate money',async()=>{
  s.control.pocketFailBefore=true;await p.getByRole('button',{name:'＋ 存一笔',exact:true}).click();let f=form('pocketSpace');await f.locator('[name=amount]').fill('7.25');await f.locator('[name=confirmed]').check();await f.locator('[type=submit]').click();await p.waitForFunction(()=>[...document.querySelectorAll('.daily-editor .sheet-note')].some(n=>n.textContent.includes('offline')));const sent=s.control.pocketRequests.at(-1);await p.reload();await p.locator('#sceneNavChat').click();await p.waitForFunction(()=>document.querySelector('#roomStatus').textContent.includes('左滑'));await open('pocketSpace');await p.getByRole('button',{name:'继续提交同一笔'}).click();await p.getByRole('button',{name:'继续提交同一笔'}).waitFor({state:'hidden'});assert.equal(s.control.pocketRequests.at(-1).p_id,sent.p_id);assert.equal(s.control.daily.pocket_entries.filter(r=>r.id===sent.p_id).length,1);
  s.control.pocketAmbiguous=true;await p.getByRole('button',{name:'＋ 存一笔',exact:true}).click();f=form('pocketSpace');await f.locator('[name=amount]').fill('3');await f.locator('[name=confirmed]').check();await f.locator('[type=submit]').click();await p.waitForFunction(()=>[...document.querySelectorAll('.daily-editor .sheet-note')].some(n=>n.textContent.includes('lost response')));const lost=s.control.pocketRequests.at(-1).p_id;await p.reload();await p.locator('#sceneNavChat').click();await p.waitForFunction(()=>document.querySelector('#roomStatus').textContent.includes('左滑'));await open('pocketSpace');assert.equal(await p.getByRole('button',{name:'继续提交同一笔'}).count(),0);assert.equal(s.control.daily.pocket_entries.filter(r=>r.id===lost).length,1);
 });
 await check('activity entry saves actual book progress; daily pages fit all six themes and five layouts',async()=>{
  await open('activitySpace');await p.locator('#activitySpace .daily-toolbar button').click();const f=form('activitySpace');await f.locator('[name=title]').fill('飞鸟集');await f.locator('[name=progress]').fill('第 48 则');await f.locator('[type=submit]').click();await saved('activitySpace');assert.match(await p.locator('#activitySpace .daily-list').textContent(),/第 48 则/);
  for(const [w,h] of [[390,844],[844,390],[820,1180],[1180,820],[1440,900]]){await p.setViewportSize({width:w,height:h});for(const theme of ['ins-light','ins-dark','warm-light','warm-dark','rain-night','moon-glass']){await p.evaluate(async value=>(await import('./ui-v2.js?v=2.6.2')).setTheme(value),theme);for(const id of ['pocketSpace','ledgerSpace','todoSpace','checkinSpace']){await open(id);await p.waitForTimeout(50);assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`${theme} ${w} ${id} page`);assert.ok(await p.locator('#'+id).evaluate(el=>el.scrollWidth<=el.clientWidth+1),`${theme} ${w} ${id} content`);}if(w===1180&&theme==='warm-light'){await open('pocketSpace');await p.screenshot({path:root+'/test-results/daily-pocket-tablet.png'});}}}
 });
 assert.deepEqual(s.errors,[]);await s.context.close();
}
