// Executes the REAL migrations in an isolated PostgreSQL WASM instance.
// Supabase's auth/storage roles and schemas are represented here; no live data is touched.
import { PGlite } from "@electric-sql/pglite";
import { pgcrypto } from "@electric-sql/pglite/contrib/pgcrypto";
import { readFile } from "node:fs/promises";
import assert from "node:assert/strict";

const db = new PGlite({ extensions: { pgcrypto } });
const a = "00000000-0000-4000-a000-000000000001";
const b = "00000000-0000-4000-a000-000000000002";
const c = "00000000-0000-4000-a000-000000000003";
let checks = 0;
async function check(label, callback) {
  await callback();
  checks++;
  console.log("PASS", label);
}
async function as(user = null) {
  await db.exec("reset role");
  await db.query("select set_config('request.jwt.claim.sub', $1, false)", [
    user || "",
  ]);
  await db.exec("set role " + (user ? "authenticated" : "anon"));
}
async function denied(sql, params = [], code = "42501") {
  await assert.rejects(db.query(sql, params), (e) => e.code === code);
}
async function scalar(sql, params = []) {
  const result = await db.query(sql, params);
  return Object.values(result.rows[0])[0];
}
async function insert(
  room,
  author,
  nonce,
  content = "hello",
  refs = [],
  created = "2000-01-01",
) {
  return (
    await db.query(
      `insert into public.messages(room_id, content, sender, sender_name, author_id, client_nonce, reply_to, created_at)
    values($1,$2,$3,'sender',$4,$5,$6::jsonb,$7) returning *`,
      [room, content, author, author, nonce, JSON.stringify(refs), created],
    )
  ).rows[0];
}
try {
  await db.exec(`
    create role anon; create role authenticated;
    create schema auth;
    create table auth.users(id uuid primary key);
    create function auth.uid() returns uuid language sql stable as
      $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
    grant usage on schema auth, public to anon, authenticated;
    create schema storage;
    create table storage.buckets(id text primary key, name text, public boolean, file_size_limit bigint);
    create table storage.objects(id uuid default gen_random_uuid(), bucket_id text, name text);
    alter table storage.objects enable row level security;
    grant usage on schema storage to anon, authenticated;
    grant all on storage.objects to anon, authenticated;
    create policy old_broad_storage on storage.objects for all using(true) with check(true);
    create table public.messages(id bigint generated by default as identity primary key, room_id text not null,
      content text not null, sender text not null, sender_name text, created_at timestamptz not null default now());
    alter table public.messages enable row level security;
    grant all on public.messages to anon, authenticated;
    grant usage,select on all sequences in schema public to anon, authenticated;
    create policy old_public_messages on public.messages for all using(true) with check(true);
    insert into messages(room_id,content,sender) values('OLDroom','legacy sentinel','device-id');
    create publication supabase_realtime;
  `);
  await db.query("insert into auth.users(id) values($1),($2),($3)", [a, b, c]);
  const foundation = await readFile(
    new URL("../supabase/migrations/20260920_mailbox_v2.sql", import.meta.url),
    "utf8",
  );
  const auth = await readFile(
    new URL(
      "../supabase/migrations/20260921_mailbox_auth.sql",
      import.meta.url,
    ),
    "utf8",
  );
  await check("both migrations execute and are re-runnable", async () => {
    await db.exec(foundation);
    await db.exec(auth);
    await db.exec(foundation);
    await db.exec(auth);
  });
  await as();
  await check("legacy anon read/write unchanged", async () => {
    assert.equal(
      await scalar("select content from messages where room_id=$1", [
        "OLDroom",
      ]),
      "legacy sentinel",
    );
    await db.query(
      "insert into messages(room_id,content,sender) values('OLDroom','still works','device-id')",
    );
  });
  await check("unauthenticated room creation denied", () =>
    denied("select mailbox_create_room('anon')"),
  );
  await as(a);
  const room = await scalar("select mailbox_create_room('小辞')");
  assert.match(room.invite, /^[a-f0-9]{64}$/);
  await check(
    "room secret is not selectable, metadata is member-only",
    async () => {
      await denied("select invite_hash from mailbox_rooms");
      assert.equal(await scalar("select count(room_id) from mailbox_rooms"), 1);
    },
  );
  const nonce = "10000000-0000-4000-a000-000000000001";
  const message = await insert(room.room_id, a, nonce);
  await check("server assigns immutable real creation time", async () =>
    assert.notEqual(new Date(message.created_at).getUTCFullYear(), 2000),
  );
  await check("idempotency rejects duplicate nonce", () =>
    denied(
      `insert into messages(room_id,content,sender,author_id,client_nonce)
    values($1,'retry',$2::text,$2::uuid,$3)`,
      [room.room_id, a, nonce],
      "23505",
    ),
  );
  await check("owner can change display date only", async () => {
    await db.query("update messages set display_date=$1 where id=$2", [
      "2024-09-04",
      message.id,
    ]);
    assert.equal(
      await scalar("select display_date::text from messages where id=$1", [
        message.id,
      ]),
      "2024-09-04",
    );
    await denied("update messages set created_at='2001-01-01' where id=$1", [
      message.id,
    ]);
    await denied("update messages set room_id='OLDroom' where id=$1", [
      message.id,
    ]);
    await denied("update messages set content='forged' where id=$1", [
      message.id,
    ]);
  });
  await check("member cannot forge another author", () =>
    denied(
      `insert into messages(room_id,content,sender,author_id,client_nonce)
    values($1,'forged',$2::text,$2::uuid,gen_random_uuid())`,
      [room.room_id, b],
    ),
  );
  await check("legacy rows cannot be moved into a protected room", () =>
    denied("update messages set room_id=$1 where room_id=$2", [
      room.room_id,
      "OLDroom",
    ]),
  );
  await check("legacy rows cannot claim authenticated ownership", () =>
    denied("update messages set author_id=$1 where room_id=$2", [a, "OLDroom"]),
  );
  await as(b);
  await check(
    "nonmember cannot read protected messages despite old USING(true)",
    async () => {
      assert.equal(
        await scalar("select count(*) from messages where room_id=$1", [
          room.room_id,
        ]),
        0,
      );
      assert.equal(
        await scalar("select count(*) from room_members where room_id=$1", [
          room.room_id,
        ]),
        0,
      );
    },
  );
  await check("self-enrolment and guessed invites denied", async () => {
    await denied("insert into room_members(room_id,user_id) values($1,$2)", [
      room.room_id,
      b,
    ]);
    await denied("select mailbox_join_room($1,$2)", [room.room_id, "bad"]);
    await denied("select mailbox_join_room($1,$2)", [
      room.room_id,
      "0".repeat(64),
    ]);
  });
  await db.query("select mailbox_join_room($1,$2)", [
    room.room_id,
    room.invite,
  ]);
  await check(
    "correct invite joins idempotently and enables read",
    async () => {
      await db.query("select mailbox_join_room($1,$2)", [room.room_id, ""]);
      assert.equal(
        await scalar("select count(*) from room_members where room_id=$1", [
          room.room_id,
        ]),
        2,
      );
      assert.equal(
        await scalar("select content from messages where id=$1", [message.id]),
        "hello",
      );
    },
  );
  await check(
    "members cannot edit others or delete protected messages",
    async () => {
      assert.equal(
        (
          await db.query(
            "update messages set display_date=$1 where id=$2 returning id",
            ["2022-01-01", message.id],
          )
        ).rows.length,
        0,
      );
      assert.equal(
        (
          await db.query("delete from messages where id=$1 returning id", [
            message.id,
          ])
        ).rows.length,
        0,
      );
      assert.equal(
        (
          await db.query(
            "update room_members set display_name='fake' where user_id=$1 returning user_id",
            [a],
          )
        ).rows.length,
        0,
      );
      await denied("update room_members set user_id=$1 where user_id=$2", [
        c,
        b,
      ]);
    },
  );
  await check("own profile accepts only bounded raster avatars", async () => {
    await db.query(
      "update room_members set display_name='朋友甲',avatar_data='data:image/png;base64,YQ==' where user_id=$1",
      [b],
    );
    await denied(
      "update room_members set avatar_data='https://tracker.example/a' where user_id=$1",
      [b],
      "22023",
    );
    await denied(
      "update room_members set avatar_data='data:image/svg+xml;base64,YQ==' where user_id=$1",
      [b],
      "22023",
    );
  });
  await check("references must exist in same room", async () => {
    await insert(room.room_id, b, crypto.randomUUID(), "reply", [
      String(message.id),
    ]);
    await assert.rejects(
      insert(room.room_id, b, crypto.randomUUID(), "bad reference", ["999999"]),
      (e) => e.code === "22023",
    );
    await assert.rejects(
      insert(room.room_id, b, crypto.randomUUID(), "bad legacy ref", ["1"]),
      (e) => e.code === "22023",
    );
  });
  await check("prepared private features remain fail-closed", async () => {
    for (const table of ["memoirs", "anniversaries", "listen_sessions"])
      await denied("select * from " + table);
    await denied(
      "insert into storage.objects(bucket_id,name) values('message-media','test')",
    );
  });
  await as(c);
  await check("unknown v2 namespace never falls back to legacy access", () =>
    denied(`insert into messages(room_id,content,sender)
    values('v2_nonexistent','attack','x')`),
  );
  await as();
  await check(
    "signed-out caller sees only the original legacy room",
    async () => {
      assert.equal(await scalar("select count(*) from messages"), 2);
      await denied("select * from room_members");
    },
  );
  await check(
    "originally disabled RLS keeps only legacy access when enabled",
    async () => {
      await db.exec(
        "reset role; alter table public.messages disable row level security; drop policy old_public_messages on public.messages;",
      );
      await db.exec(auth);
      await as();
      assert.equal(await scalar("select count(*) from messages"), 2);
      await db.query(
        "insert into messages(room_id,content,sender) values('OLDroom','compatible','device-id')",
      );
      assert.equal(
        await scalar("select count(*) from messages where room_id=$1", [
          room.room_id,
        ]),
        0,
      );
    },
  );
  console.log(
    `\n${checks} PostgreSQL authorization checks passed. Live Supabase was not modified.`,
  );
} finally {
  await db.close();
}
