import assert from 'node:assert/strict';
export async function runInteractions({setup,check,secureId,user,friend,fixture,root}){
 const rows=[fixture(1,secureId,'第一段留言',user,{author_id:user}),fixture(2,secureId,'第二段留言',friend,{author_id:friend}),fixture(3,secureId,'第三段留言',friend,{author_id:friend})];
 const s=await setup({secure:true,rows}),p=s.page;await p.waitForFunction(()=>document.querySelector('#roomStatus').textContent.includes('左滑'));
 const open=async()=>{await p.locator('#composeMore').click();await p.locator('#importBtn').click();await p.waitForFunction(()=>!document.querySelector('#ocrChoose').disabled);};
 const close=async()=>p.locator('[data-close=importScrim]').click();
 const select=async(...ids)=>{await p.locator(`[data-message-id="${ids[0]}"] .bubble`).dispatchEvent('contextmenu');for(const id of ids.slice(1))await p.locator(`[data-message-id="${id}"] .bubble`).click();};
 const files=names=>names.map((name,i)=>({name,mimeType:'image/png',buffer:Buffer.from('screenshot:'+name)}));
 await check('long press selects, scroll motion cancels, and normal messages have no inline action labels',async()=>{
  assert.equal(await p.locator('[data-quote-id],[data-date-id]').count(),0);const b=p.locator('[data-message-id="1"] .bubble');await b.dispatchEvent('pointerdown',{button:0,clientX:100,clientY:150,pointerId:1});await b.dispatchEvent('pointermove',{clientX:100,clientY:200,pointerId:1});await p.waitForTimeout(480);assert.equal(await p.locator('#selectionBar').isVisible(),false);
  await b.dispatchEvent('pointerdown',{button:0,clientX:100,clientY:150,pointerId:1});await p.locator('#selectionBar').waitFor();await b.dispatchEvent('pointerup',{pointerId:1});await b.dispatchEvent('click');assert.equal(await p.locator('#selectionCount').textContent(),'已选 1 条');await p.locator('[data-message-id="2"] .bubble').click();assert.equal(await p.locator('#selectionCount').textContent(),'已选 2 条');await p.locator('#selectQuote').click();assert.equal(await p.locator('#quoteTray').isVisible(),true);assert.equal(await p.locator('#composer').isVisible(),true);
 });
 await check('favorites and local deletion survive reload and can be restored without deleting remote data',async()=>{
  await select(1,2);await p.locator('#selectFavorite').click();await p.reload();await p.locator('[data-message-id="1"] .bubble').waitFor();assert.equal(await p.locator('.favorite-mark').count(),2);await select(1,2);await p.locator('#selectDelete').click();await p.locator('#noticeConfirm').click();await p.waitForFunction(()=>document.querySelectorAll('.msg').length===1);assert.equal(s.control.records.length,3);await p.reload();await p.locator('[data-message-id="3"]').waitFor();assert.equal(await p.locator('.msg').count(),1);await p.locator('#menuBtn').click();await p.locator('#deletedBtn').click();await p.locator('.collection-card button').first().click();await p.locator('.collection-card button').first().click();await p.locator('[data-close=collectionScrim]').click();assert.equal(await p.locator('.msg').count(),3);
 });
 await check('merged and separate forward preserve source text; ambiguous send retry reuses nonce',async()=>{
  await select(1,2);await p.locator('#selectMerge').click();s.control.ambiguousNext=true;await p.locator('#forwardSend').click();await p.waitForFunction(()=>document.querySelector('#forwardNote').textContent.includes('保留进度'));const nonce=s.control.sends.at(-1).client_nonce;await p.locator('#forwardSend').click();await p.waitForFunction(()=>document.querySelector('#forwardScrim').hidden);assert.equal(s.control.sends.at(-1).client_nonce,nonce);assert.equal(s.control.records.filter(r=>r.content.startsWith('【合并转发】')).length,1);assert.equal(await p.locator('.forward-record').count(),1);await select(1,2);await p.locator('#selectForward').click();await p.locator('#forwardSend').click();await p.waitForFunction(()=>document.querySelector('#forwardScrim').hidden);assert.equal(s.control.records.filter(r=>r.content.startsWith('[转发')).length,2);
 });
 await check('forwarded media is copied to a distinct private path',async()=>{
  await p.locator('#attachBtn').click();await p.locator('#attachmentFile').setInputFiles({name:'shared.txt',mimeType:'text/plain',buffer:Buffer.from('attachment body')});await p.locator('#attachmentSend').click();await p.waitForFunction(()=>document.querySelector('#attachmentScrim').hidden);const original=s.control.records.at(-1);await select(original.id);await p.locator('#selectForward').click();await p.locator('#forwardSend').click();await p.waitForFunction(()=>document.querySelector('#forwardScrim').hidden);const copy=s.control.records.at(-1);assert.equal(copy.media_name,'shared.txt');assert.notEqual(copy.media_path,original.media_path);assert.deepEqual(s.control.uploads.get(copy.media_path).buffer,s.control.uploads.get(original.media_path).buffer);
 });
 await open();
 await check('directory import is read-only, recursive, content-deduplicated and sorted by screenshot time',async()=>{
  await p.evaluate(()=>{const f=(name,text)=>({kind:'file',name,getFile:async()=>new File([text],name,{type:name.endsWith('.txt')?'text/plain':'image/png',lastModified:1})});window.showDirectoryPicker=async options=>{window.directoryOptions=options;return {async* values(){yield f('Screenshot_20260921_090000.png','later');yield {kind:'directory',name:'past',async* values(){yield f('Screenshot_20260920_090000.png','earlier');yield f('renamed.png','later');yield f('notes.txt','text');}};}};};});await p.locator('#ocrChoose').click();await p.waitForFunction(()=>document.querySelector('#ocrQueueCount').textContent.includes('2 张')).catch(async e=>{console.log('Directory debug',await p.locator('#ocrStatus').textContent(),s.errors);throw e;});assert.equal(await p.evaluate(()=>window.directoryOptions.mode),'read');const names=await p.locator('#ocrQueue strong').allTextContents();assert.deepEqual(names,['Screenshot_20260920_090000.png','Screenshot_20260921_090000.png']);await p.locator('#ocrInvert').click();assert.match(await p.locator('#ocrQueueCount').textContent(),/选中 0 张/);await p.locator('#ocrAll').click();assert.match(await p.locator('#ocrQueueCount').textContent(),/选中 2 张/);
 });
 await check('unsupported directory picker falls back to a multiple-file chooser',async()=>{
  await p.evaluate(()=>window.showDirectoryPicker=async()=>{throw new DOMException('unsupported','NotSupportedError');});const chooser=p.waitForEvent('filechooser');await p.locator('#ocrChoose').click();const picker=await chooser;assert.equal(picker.isMultiple(),true);await picker.setFiles([]);
 });
 await check('batch OCR skips processed screenshots, retains editable dates, and persists across reload',async()=>{
  await p.locator('#ocrRecognize').click();await p.waitForFunction(()=>document.querySelectorAll('.import-row').length===2&&!document.querySelector('#importSend').disabled);assert.equal(await p.locator('.import-row input[type=date]').first().inputValue(),'2026-09-18');const calls=await p.evaluate(()=>window.ocrCalls);await p.locator('#ocrRecognize').click();assert.equal(await p.evaluate(()=>window.ocrCalls),calls);await p.locator('.import-row textarea').first().fill('编辑后保留的正文');await close();await p.reload();await p.locator('#composeMore').waitFor();await open();await p.locator('.import-row textarea').first().waitFor();assert.equal(await p.locator('.import-row textarea').first().inputValue(),'编辑后保留的正文');await p.locator('#ocrNewOnly').click();assert.match(await p.locator('#ocrQueueCount').textContent(),/选中 0 张/);assert.match(await p.locator('#ocrDraftCount').textContent(),/选中 0 段/);await p.locator('#draftAll').click();
 });
 await check('side filtering and merged import require confirmation; retry sends a batch only once',async()=>{
  await p.locator('.import-row select').nth(1).selectOption('right');await p.locator('#ocrSide').selectOption('right');assert.match(await p.locator('#ocrDraftCount').textContent(),/选中 1 段/);await p.locator('#ocrSide').selectOption('all');await p.locator('#ocrMode').selectOption('merged');const before=s.control.sends.length;s.control.ambiguousNext=true;await p.locator('#importSend').click();assert.equal(s.control.sends.length,before);await p.locator('#noticeConfirm').click();await p.waitForFunction(()=>document.querySelector('#ocrStatus').textContent.includes('保留编号'));assert.equal(await p.locator('#importClear').isDisabled(),true);assert.equal(await p.locator('.import-row textarea').first().isDisabled(),true);const nonce=s.control.sends.at(-1).client_nonce;await p.locator('#importSend').click();await p.locator('#noticeConfirm').click();await p.waitForFunction(()=>document.querySelectorAll('.import-row.sent').length===2);assert.equal(s.control.sends.at(-1).client_nonce,nonce);assert.equal(s.control.records.filter(r=>r.client_nonce===nonce).length,1);assert.equal(s.control.records.at(-1).display_date,'2026-09-18');assert.match(s.control.records.at(-1).content,/编辑后保留的正文/);assert.match(s.control.records.at(-1).content,/我/);
 });
 await check('many screenshots paginate, cancellation preserves finished work, reselected processed images stay skipped',async()=>{
  await p.locator('#importClear').click();await p.locator('#noticeConfirm').click();await p.waitForFunction(()=>document.querySelector('#ocrQueueCount').textContent.startsWith('0 张'));await p.locator('#ocrFile').setInputFiles(files(Array.from({length:25},(_,i)=>`Screenshot_202609${String(i%20+1).padStart(2,'0')}_10${String(i).padStart(2,'0')}00.png`)));await p.waitForFunction(()=>document.querySelector('#ocrQueueCount').textContent.includes('25 张')&&!document.querySelector('#ocrRecognize').disabled);assert.equal(await p.locator('.screenshot-row').count(),20);await p.locator('#queueNext').click();assert.equal(await p.locator('.screenshot-row').count(),5);await p.locator('#queuePrev').click();await p.evaluate(()=>window.ocrSlow=true);await p.locator('#ocrRecognize').click();await p.waitForFunction(()=>document.querySelectorAll('.import-row').length>=1);await p.locator('#ocrCancel').click();await p.waitForFunction(()=>!document.querySelector('#ocrRecognize').disabled);const completed=await p.locator('.import-row').count();assert.ok(completed>=1&&completed<25);await p.evaluate(()=>window.ocrSlow=false);await p.locator('#importClear').click();await p.locator('#noticeConfirm').click();await p.locator('#ocrFile').setInputFiles(files(['Screenshot_20260901_100000.png']));await p.waitForFunction(()=>document.querySelector('#ocrQueueCount').textContent.includes('1 张')&&!document.querySelector('#ocrRecognize').disabled);assert.match(await p.locator('#ocrQueue').textContent(),/已处理/);assert.match(await p.locator('#ocrQueueCount').textContent(),/选中 0 张/);
 });
 await check('batch dialog and selection actions fit every theme on phone, tablet and desktop',async()=>{
  for(const [device,width,height] of [['phone',320,680],['tablet',820,1180],['landscape',1180,820],['desktop',1440,900],['short',844,390]]){await p.setViewportSize({width,height});for(const theme of ['ins-light','ins-dark','warm-light','warm-dark']){await p.evaluate(theme=>document.documentElement.dataset.theme=theme,theme);assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));const dialog=await p.locator('#importScrim .sheet').boundingBox();assert.ok(dialog.width<=width&&dialog.height<=height);assert.ok(await p.locator('#importScrim .sheet').evaluate(el=>el.scrollWidth<=el.clientWidth+1));}if(device==='phone')await p.screenshot({path:root+'/test-results/p2-batch-phone.png'});await close();await select(1,2);const bar=await p.locator('#selectionBar').boundingBox();assert.ok(bar.x+bar.width<=width+1&&bar.y+bar.height<=height+1);assert.ok((await p.locator('#messages').boundingBox()).height>80);if(device==='phone')await p.screenshot({path:root+'/test-results/p2-select-phone.png'});await p.locator('#selectionCancel').click();await open();}
 });
 await check('a partially delivered import resumes only unfinished entries',async()=>{
  await p.locator('#importClear').click();await p.locator('#noticeConfirm').click();await p.locator('.manual-import summary').click();await p.locator('#ocrManual').fill('批次第一段\n\n批次第二段');await p.locator('#ocrParse').click();await p.locator('#ocrMode').selectOption('separate');s.control.failOnSend=s.control.sends.length+2;await p.locator('#importSend').click();await p.locator('#noticeConfirm').click();await p.waitForFunction(()=>document.querySelector('#ocrStatus').textContent.includes('保留编号'));assert.equal(await p.locator('.import-row.sent').count(),1);const nonce=s.control.sends.at(-1).client_nonce;await p.locator('#importSend').click();await p.locator('#noticeConfirm').click();await p.waitForFunction(()=>document.querySelectorAll('.import-row.sent').length===2);assert.equal(s.control.sends.at(-1).client_nonce,nonce);assert.equal(s.control.records.filter(r=>r.content==='批次第一段').length,1);assert.equal(s.control.records.filter(r=>r.content==='批次第二段').length,1);
 });
 await check('a late import response stays in its original room and preserves the next room draft',async()=>{
  await p.locator('#importClear').click();await p.locator('#noticeConfirm').click();await p.locator('#ocrManual').fill('旧房间的导入');await p.locator('#ocrParse').click();s.control.delayMs=3500;await p.locator('#importSend').click();const request=p.waitForRequest(r=>r.method()==='POST'&&r.url().includes('/rest/v1/messages'));await p.locator('#noticeConfirm').click();await request;await close();await p.locator('#backBtn').click();await s.join('NextRoom2');await open();await p.locator('#ocrManual').fill('新房间的草稿');await p.locator('#ocrParse').click();await p.evaluate(async({secureId,user})=>{const {screenshotRecord}=await import('./screenshot-store.js?v=2.3.0');for(let n=0;n<120;n++){const saved=await screenshotRecord(secureId+'.'+user,'batch');if(saved?.drafts?.some(r=>r.text==='旧房间的导入'&&r.sent))return;await new Promise(r=>setTimeout(r,50));}throw Error('Late import was not persisted in its original room');},{secureId,user});assert.equal(await p.locator('.import-row textarea').inputValue(),'新房间的草稿');assert.equal(await p.locator('.msg').count(),0);assert.equal(s.control.records.filter(r=>r.content==='旧房间的导入'&&r.room_id===secureId).length,1,JSON.stringify({last:s.control.records.slice(-3),sends:s.control.sends.slice(-2),secureId}));s.control.delayMs=0;
 });
 assert.deepEqual(s.errors,[]);await s.context.close();
}
