import {memoryControl} from './memory-controls.mjs';
import assert from 'node:assert/strict';
export async function runMemories({setup,check,secureId,user,friend,fixture,root}){
 const s=await setup({secure:true,rows:[fixture(1,secureId,'日落以后，我们一起去散步。',friend,{author_id:friend,display_date:'2026-09-20'}),fixture(2,secureId,'记住今天的晚风。',user,{author_id:user,display_date:'2026-09-20'}),fixture(3,secureId,'下一次去看看海。',friend,{author_id:friend,display_date:'2026-09-21'})]}),p=s.page;
 await p.waitForFunction(()=>document.querySelector('#roomStatus').textContent.includes('左滑'));await p.locator('#relationHandle').click();await p.locator('[data-open-view=wall]').click();await p.waitForTimeout(200);
 await check('memory notes show actual sources, flip, edit their backs and leave the chat untouched',async()=>{
  const card=p.locator('[data-memory-id="message:1"]');await card.getByRole('button',{name:'翻面',exact:true}).click();assert.equal(await card.evaluate(e=>e.classList.contains('flipped')),true);await card.getByRole('button',{name:'详情',exact:true}).click();await p.getByRole('button',{name:'补充记录',exact:true}).click();await p.locator('#memoryEditor [name=back]').fill('那天一路聊了很多。');await p.locator('#memoryEditor [name=tags]').fill('散步，晚风');await p.locator('#memoryEditor [name=location]').fill('学校');await p.locator('#memoryEditor [type=submit]').click();await p.locator('#memoryEditor').waitFor({state:'hidden'});assert.equal(s.control.records[0].content,'日落以后，我们一起去散步。');assert.equal(s.control.memoryProfiles[0].data.annotations['message:1'].back,'那天一路聊了很多。');await memoryControl(p,'#memorySearchToggle');await p.locator('#memoryTag').fill('晚风');assert.deepEqual(await p.locator('.memory-card').evaluateAll(cards=>cards.map(c=>c.dataset.memoryId).sort()),['message:1','message:2']);await p.locator('#memoryClear').click();await memoryControl(p,'#memorySearchToggle');
 });
 await check('clue board draws meaningful links, saves dragging and flashlight follows a pointer after scrolling',async()=>{
  await memoryControl(p,'[data-memory-mode=board]');assert.ok(await p.locator('.clue-lines line').count()>0);assert.match(await p.locator('.clue-lines line').first().getAttribute('data-relation'),/同一天/);const card=p.locator('[data-memory-id="message:3"]'),b=await card.boundingBox();await p.mouse.move(b.x+40,b.y+45);await p.mouse.down();await p.mouse.move(b.x+100,b.y+95,{steps:5});await p.mouse.up();await p.waitForTimeout(100);assert.ok(s.control.memoryProfiles[0].data.positions['message:3']);await p.locator('#memoryLight').click();const stage=p.locator('.clue-stage');await stage.evaluate(e=>{e.scrollLeft=120;e.scrollTop=80;});const r=await stage.boundingBox();await p.mouse.move(r.x+100,r.y+110);await p.mouse.down();await p.mouse.move(r.x+150,r.y+160,{steps:5});await p.mouse.up();await p.waitForTimeout(80);assert.ok(await stage.evaluate(e=>Math.abs(parseFloat(e.style.getPropertyValue('--light-x'))-(150-e.clientLeft))<3));assert.equal(await stage.evaluate(e=>e.classList.contains('dark')),true);await p.screenshot({path:root+'/test-results/memory-flashlight.png'});await p.locator('#memoryLight').click();
 });
 await check('record wall rotates with touch and inertia and exposes distinct memories through keyboard too',async()=>{
  await memoryControl(p,'[data-memory-mode=disc]');const disc=p.locator('.memory-disc');await disc.focus();const old=await disc.getAttribute('aria-valuenow');await p.keyboard.press('ArrowDown');assert.notEqual(await disc.getAttribute('aria-valuenow'),old);const r=await p.locator('.disc-stage').boundingBox();await p.mouse.move(r.x+r.width-35,r.y+200);await p.mouse.down();await p.mouse.move(r.x+r.width-35,r.y+280,{steps:8});await p.mouse.up();const angle=await disc.evaluate(e=>e.style.getPropertyValue('--disc-angle'));await p.waitForTimeout(100);assert.notEqual(await disc.evaluate(e=>e.style.getPropertyValue('--disc-angle')),angle);
 });
 await check('new notes save real entries, daily summaries can be disabled, and all three views fit six themes/five sizes',async()=>{
  await memoryControl(p,'[data-memory-mode=notes]');await memoryControl(p,'#memoryAdd');await p.locator('#memoryEditor [name=title]').fill('一张新的便签');await p.locator('#memoryEditor [name=body]').fill('把普通的一天留下来。');await p.locator('#memoryEditor [type=submit]').click();await p.locator('#memoryEditor').waitFor({state:'hidden'});await memoryControl(p,'#memoryToolsToggle');await p.locator('#memorySummary').uncheck();await p.locator('[aria-label="收起回忆工具"]').click();await p.waitForTimeout(100);assert.equal(s.control.daily.space_entries[0].kind,'memory');assert.equal(s.control.memoryProfiles[0].data.summary,false);
  for(const [w,h] of [[390,844],[844,390],[820,1180],[1180,820],[1440,900]]){await p.setViewportSize({width:w,height:h});for(const theme of ['ins-light','ins-dark','warm-light','warm-dark','rain-night','moon-glass']){await p.evaluate(async t=>(await import('./ui-v2.js?v=2.7.2')).setTheme(t),theme);for(const mode of ['notes','board','disc']){await memoryControl(p,`[data-memory-mode=${mode}]`);assert.ok(await p.locator('#wallSpace').evaluate(e=>e.scrollWidth<=e.clientWidth+1),`${theme} ${w} ${mode}`);}if(w===390&&theme==='ins-dark')await p.screenshot({path:root+'/test-results/memory-disc-phone.png'});if(w===1180&&theme==='warm-light'){await memoryControl(p,'[data-memory-mode=notes]');await p.screenshot({path:root+'/test-results/memory-notes-tablet.png'});}}}
 });
 assert.deepEqual(s.errors,[]);await s.context.close();
}
