import assert from 'node:assert/strict';
function wav(frequency=220){const n=8000*60,b=Buffer.alloc(44+n*2);b.write('RIFF');b.writeUInt32LE(36+n*2,4);b.write('WAVEfmt ',8);b.writeUInt32LE(16,16);b.writeUInt16LE(1,20);b.writeUInt16LE(1,22);b.writeUInt32LE(8000,24);b.writeUInt32LE(16000,28);b.writeUInt16LE(2,32);b.writeUInt16LE(16,34);b.write('data',36);b.writeUInt32LE(n*2,40);for(let i=0;i<n;i++)b.writeInt16LE(Math.round(Math.sin(i*frequency/8000)*1000),44+i*2);return b;}
export async function runMusic({setup,check,secureId,user,friend,fixture,root}){
 const s=await setup({secure:true,rows:[fixture(1,secureId,'一起听',friend,{author_id:friend})]}),p=s.page;
 await p.waitForFunction(()=>document.querySelector('#roomStatus').textContent.includes('左滑'));await p.locator('#relationHandle').click();await p.locator('#listenBtn').click();
 await check('music imports multiple local files, preserves lyrics, renders record and plays actual audio',async()=>{
  await p.locator('#musicImport').click();await p.locator('#listenFile').setInputFiles([{name:'one.wav',mimeType:'audio/wav',buffer:wav()},{name:'two.wav',mimeType:'audio/wav',buffer:wav(330)}]);await p.waitForFunction(()=>document.querySelector('#musicImportCount').textContent==='2');await p.locator('#lyricsFile').setInputFiles({name:'one.lrc',mimeType:'text/plain',buffer:Buffer.from('[00:00.00]晴天的旋律\n[00:03.00]一起听到夜晚')});await p.waitForFunction(()=>document.querySelector('#musicLyricsStatus').textContent.includes('2 行'));await p.locator('#musicImportSave').click();await p.waitForFunction(()=>document.querySelector('#lyrics').textContent.includes('晴天'));assert.equal(s.control.music.music_tracks.length,2);assert.ok(s.control.music.music_tracks.every(t=>t.visibility==='private'));await p.locator('#listenToggle').click();await p.waitForFunction(()=>document.querySelector('#listenAudio').currentTime>0.2);assert.equal(await p.locator('#musicRecord').evaluate(e=>e.classList.contains('is-playing')),true);await p.locator('#listenToggle').click();
 });
 const key=s.control.music.music_tracks[0].track_key;
 await check('A like creates one note; B like creates two and the common-like filter contains the song',async()=>{
  await p.locator('#musicLike').click();await p.waitForFunction(()=>document.querySelectorAll('#trackLikes .music-like-note.is-liked').length===1);assert.equal(s.control.music.music_likes[0].owner_user_id,user);s.control.music.music_likes.push({room_id:secureId,owner_user_id:friend,track_key:key});s.control.music.music_colors.push({room_id:secureId,owner_user_id:friend,color:'#a1b2c3'});await p.evaluate(()=>document.dispatchEvent(new Event('visibilitychange')));await p.waitForFunction(()=>document.querySelectorAll('#trackLikes .music-like-note.is-liked').length===2);await p.locator('[data-music-page=library]').click();await p.locator('[data-filter=both]').click();assert.equal(await p.locator('.music-track').count(),1);await p.locator('[data-music-page=player]').click();
 });
 await check('lyrics switch between island, status text, off and immersive view; mini record expands in chat',async()=>{
  await p.locator('.lyric-settings summary').click();await p.locator('#lyricMode').selectOption('island');await p.locator('#relationClose').click();await p.locator('#topLyricLine').click();await p.locator('#islandControls').waitFor();assert.equal(await p.locator('#islandControls .island-transport button').count(),5);await p.locator('#topLyricLine').click();await p.locator('#relationHandle').click();await p.locator('#listenBtn').click();await p.locator('#lyricMode').selectOption('status');assert.equal(await p.locator('#topLyric').getAttribute('data-mode'),'status');await p.locator('#lyricMode').selectOption('off');assert.equal(await p.locator('#topLyric').isVisible(),false);await p.locator('#musicRecord').click();await p.locator('#musicImmersive').waitFor();assert.match(await p.locator('#immersiveLyrics').textContent(),/晴天/);await p.locator('#lyricsBack').click();await p.locator('#relationClose').click();await p.locator('#miniRecord').click();assert.equal(await p.locator('#listenMini').evaluate(e=>e.classList.contains('expanded')),true);await p.locator('#miniListenOpen').click();
 });
 await check('shared playlists add, reorder and move songs; private favorite remains private',async()=>{
  await p.locator('#musicFavorite').click();await p.waitForFunction(()=>document.querySelector('#listenStatus')!==null);await p.locator('[data-music-page=library]').click();await p.locator('[data-filter=all]').click();await p.locator('#playlistNew').click();await p.locator('#musicEditor [name=title]').fill('共同歌单');await p.locator('#musicEditor [name=visibility]').selectOption('shared');await p.locator('#musicEditor [type=submit]').click();await p.locator('#musicEditor').waitFor({state:'hidden'});const shared=s.control.music.music_playlists.find(x=>x.title==='共同歌单');assert.ok(s.control.music.music_playlists.find(x=>x.title==='我的收藏'&&x.visibility==='private'));
  for(const k of s.control.music.music_tracks.map(t=>t.track_key)){const row=p.locator(`.music-track[data-key="${k}"]`);await row.locator('.music-track-menu summary').click();await row.locator('select').selectOption(shared.id);await row.getByRole('button',{name:'加入',exact:true}).click();await p.waitForTimeout(60);}await p.locator('#playlistSelect').selectOption(shared.id);assert.equal(await p.locator('.music-track').count(),2);const before=[...shared.track_keys];await p.locator('.music-track').first().locator('.music-track-menu summary').click();await p.locator('.music-track').first().getByRole('button',{name:'↓',exact:true}).click();await p.waitForTimeout(100);assert.deepEqual(shared.track_keys,[before[1],before[0]]);
 });
 await check('reports show server totals with exact seconds, a waveform and calendar across six themes/five layouts',async()=>{
  s.control.musicReport={total_seconds:22356,daily:[{day:'2026-09-16',seconds:22356}],tracks:[{track_key:key,seconds:22356,plays:4,last_played:'2026-09-16T10:00:00Z'}]};await p.locator('[data-music-page=report]').click();await p.locator('#reportDate').fill('2026-09-30');await p.locator('#reportDate').dispatchEvent('change');await p.waitForFunction(()=>document.querySelector('.music-best')?.textContent.includes('6 小时 12 分 36 秒'));assert.equal(await p.locator('.music-wave-bar').count(),30);assert.equal(await p.locator('.music-heat-day').count(),30);
  for(const [w,h] of [[390,844],[844,390],[820,1180],[1180,820],[1440,900]]){await p.setViewportSize({width:w,height:h});for(const theme of ['ins-light','ins-dark','warm-light','warm-dark','rain-night','moon-glass']){await p.evaluate(async t=>(await import('./ui-v2.js?v=2.7.4')).setTheme(t),theme);for(const tab of ['player','library','report']){await p.locator(`[data-music-page=${tab}]`).click();assert.ok(await p.locator('#listenScrim').evaluate(e=>e.scrollWidth<=e.clientWidth+1),`${theme} ${w} ${tab}`);}if(w===390&&theme==='warm-dark'||w===1180&&theme==='ins-light'){await p.locator('[data-music-page=player]').click();await p.screenshot({path:root+`/test-results/music-${w}-${theme}.png`});}}}
 });
 await check('local library and lyrics recover after reload without playing or sharing automatically',async()=>{
  await p.reload();await p.locator('#sceneNavChat').click();await p.locator('#listenMini').waitFor();await p.locator('#relationHandle').click();await p.locator('#listenBtn').click();assert.equal(await p.locator('#listenAudio').evaluate(e=>e.paused),true);assert.equal(await p.locator('#listenSync').isChecked(),false);assert.match(await p.locator('#lyrics').textContent(),/晴天/);
 });
 assert.deepEqual(s.errors,[]);await s.context.close();
}
